import React, { createContext, useContext, useEffect, useState, ReactNode } from "react";

export type Language = "en" | "ar" | "ur";

const LANGUAGE_ORDER: Language[] = ["ar", "en", "ur"];
const RTL_LANGUAGES: Language[] = ["ar", "ur"];

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Header
    siteName: "Trucks",
    home: "Home",
    inventory: "Inventory",
    sellYourTruck: "Sell Your Truck",
    loginTitle: "Log in",
    loginSubtitle: "Sign in to list your truck on Trucks.",
    loginAction: "Log in",
    loginSuccess: "Welcome back!",
    loginFailed: "Could not log in. Check your email and password.",
    signupTitle: "Create an account",
    signupSubtitle: "Sign up to post your truck listing.",
    signupAction: "Sign up",
    signupSuccess: "Account created!",
    signupFailed: "Could not sign up. Try a different email.",
    email: "Email",
    password: "Password",
    confirmPassword: "Confirm password",
    firstName: "First name",
    lastName: "Last name",
    mobileNumber: "Mobile number",
    accountType: "Account type",
    accountTypeQuestion: "How will you use Trucks?",
    accountTypeIndividual: "Individual",
    accountTypeCompany: "Company / Establishment",
    accountTypeContinue: "Continue",
    changeAccountType: "Change account type",
    companyNameRequired: "Company name is required.",
    crNumberLabel: "Commercial registration number (CR)",
    crNumberPlaceholder: "10-digit CR number",
    crNumberInvalid: "Enter a valid 10-digit commercial registration number.",
    hasVatLabel: "This establishment has a VAT number",
    vatNumberLabel: "VAT number",
    vatNumberPlaceholder: "15 digits, starts and ends with 3",
    vatNumberInvalid: "Enter a valid 15-digit VAT number (starts and ends with 3).",
    passwordMismatch: "Passwords do not match.",
    noAccount: "Don't have an account?",
    haveAccount: "Already have an account?",
    signUp: "Sign up",
    logIn: "Log in",
    logout: "Log out",
    signedInAs: "Signed in as",
    profileAccount: "Account",
    profileTitle: "Your account",
    profileSubtitle: "Buyer inquiries about your listings.",
    accountDetails: "Account details",
    fullNameLabel: "Name",
    yes: "Yes",
    no: "No",
    companyProfileTitle: "Company profile",
    companyProfileDesc: "Shown to buyers on your listings and used for how they reach you.",
    registeredCompanyInfo: "Registered company info",
    companyLogoLabel: "Company logo",
    uploadLogo: "Upload logo",
    changeLogo: "Change logo",
    removeLogo: "Remove",
    logoUploadFailed: "Could not upload logo. Try again.",
    additionalPhonesLabel: "Additional contact numbers",
    additionalPhonesHelp: "Add extra numbers buyers can use to reach your company (e.g. a sales line).",
    addPhoneNumber: "Add number",
    removeNumber: "Remove number",
    representativeNameLabel: "Responsible representative — name",
    representativePhoneLabel: "Responsible representative — phone",
    saveCompanyProfile: "Save company profile",
    companyProfileUpdated: "Company profile updated.",
    companyProfileUpdateFailed: "Could not update company profile.",
    companyStatusPending: "Pending review",
    companyStatusApproved: "Approved",
    companyStatusRejected: "Rejected",
    companyStatusPendingHelp:
      "Your company account is awaiting admin review. You'll be able to list vehicles once approved.",
    companyStatusRejectedHelp:
      "Your company account was not approved. Check your details and commercial registration document, then contact support if you believe this is a mistake.",
    crDocumentLabel: "Commercial registration document",
    crDocumentHelp: "Upload a copy of your commercial registration certificate (PDF, JPG, PNG, or WebP).",
    crDocumentRequired: "Please attach your commercial registration document.",
    uploadCrDocument: "Upload document",
    replaceCrDocument: "Replace document",
    viewCrDocument: "View document",
    noCrDocument: "No document uploaded yet.",
    crDocumentUploadFailed: "Could not upload the document. Try again.",
    crDocumentUploadFailedAfterSignup:
      "Account created, but the document upload failed. Add it from your account page.",
    termsRequired: "You must agree to the Terms and Conditions to continue.",
    agreeToTermsPrefix: "I agree to the",
    termsAndConditionsLink: "Terms and Conditions",
    termsContent:
      "1. Acceptance of terms\nBy creating an account you agree to use Trucks responsibly and in accordance with these terms.\n\n2. Account responsibility\nYou are responsible for the accuracy of the information you provide, including company and contact details, and for keeping your login credentials secure.\n\n3. Listings\nListings must be accurate and describe vehicles you own or are authorized to sell. Trucks may remove listings that are misleading, fraudulent, or violate applicable law.\n\n4. Marketplace role\nTrucks provides a platform connecting buyers and sellers. Trucks is not a party to any sale between users and does not guarantee the condition, legality, or value of any listed vehicle.\n\n5. Company verification\nCompany accounts are subject to review, including verification of the commercial registration document, before they may publish listings.\n\n6. Prohibited conduct\nYou may not use the platform for unlawful purposes, to post fraudulent listings, or to harass other users.\n\n7. Limitation of liability\nTrucks is not liable for disputes, losses, or damages arising from transactions between users.\n\n8. Changes\nThese terms may be updated from time to time; continued use of the platform constitutes acceptance of the updated terms.",
    adminNavLink: "Admin",
    adminCompaniesTitle: "Company accounts",
    adminCompaniesSubtitle: "Review company signups and approve or reject their access to list vehicles.",
    adminAllCompanies: "All",
    adminNoCompanies: "No company accounts in this view.",
    adminLoadFailed: "Could not load company accounts.",
    adminApprove: "Approve",
    adminReject: "Reject",
    adminStatusUpdated: "Status updated.",
    adminStatusUpdateFailed: "Could not update status.",
    adminArchiveListing: "Archive listing",
    adminDeleteListing: "Delete listing",
    adminConfirmDelete: "Permanently delete this listing? This cannot be undone.",
    adminConfirmArchive: "Archive this listing? It will be hidden from the public inventory.",
    adminListingDeleted: "Listing deleted.",
    adminListingDeleteFailed: "Could not delete listing.",
    adminListingArchived: "Listing archived.",
    adminListingArchiveFailed: "Could not archive listing.",
    adminContactMessagesNavLink: "Messages",
    adminContactMessagesTitle: "Contact messages",
    adminContactMessagesSubtitle: "Messages submitted through the site's contact form.",
    adminUnreadMessages: "Unread",
    adminNoContactMessages: "No messages in this view.",
    adminMarkRead: "Mark as read",
    contactPageTitle: "Contact us",
    contactPageSubtitle: "Send us a message and our team will get back to you.",
    contactNameLabel: "Name",
    contactSubjectLabel: "Subject",
    contactMessageLabel: "Message",
    contactSubmit: "Send message",
    contactSuccess: "Your message has been sent. We'll be in touch soon.",
    contactFailed: "Could not send your message. Try again.",
    securitySettings: "Security",
    changePasswordTitle: "Change password",
    currentPasswordLabel: "Current password",
    newPasswordLabel: "New password",
    confirmNewPasswordLabel: "Confirm new password",
    savePassword: "Update password",
    passwordUpdated: "Password updated.",
    passwordMismatchProfile: "New passwords do not match.",
    passwordMinEight: "Password must be at least 8 characters.",
    changePhoneTitle: "Mobile number",
    changePhoneIntro:
      "To change your number, we send a verification code to your current number.",
    phoneChangeNoNumber: "No number on file. Enter your password and the number you want to use.",
    accountPasswordLabel: "Account password",
    sendCode: "Send verification code",
    codeSentToast: "A verification code has been sent to your number.",
    devCodeHint: "Development: your code is",
    verificationCodeLabel: "Verification code",
    twoFactorTitle: "Verification required",
    twoFactorSubtitle: "Enter the verification code sent to you to finish logging in.",
    confirmTwoFactor: "Verify",
    signupVerifyTitle: "Verify your email",
    signupVerifySubtitle: "We've sent a verification code to your email. Enter it below to finish creating your account.",
    confirmSignupCode: "Verify & create account",
    resendCode: "Resend code",
    resendCodeIn: "Resend code in",
    signupVerifyFailed: "Could not verify the code. Try again.",
    newPhoneLabel: "New mobile number",
    confirmPhoneChange: "Save new number",
    phoneUpdated: "Mobile number updated.",
    phoneStep2Hint: "Enter the code you received, then your new number.",
    manageSecuritySettings: "Security",
    hideSecuritySettings: "Hide",
    myAdverts: "My adverts",
    myAdvertsTitle: "My adverts",
    myAdvertsSubtitle: "Listings you have published — open or edit any of them.",
    myAdvertsEmpty: "You have not listed any trucks yet.",
    editListing: "Edit listing",
    editListingTitle: "Edit listing",
    editListingDesc: "Update your listing details and photos. Save when you are done.",
    listingUpdatedSuccess: "Listing updated.",
    editNotOwner: "You can only edit your own listings.",
    saveListing: "Save changes",
    btnReserved: "Reserved",
    btnSold: "Sold",
    btnBackToActive: "Back to active",
    btnBackToActiveHelp:
      "Cancel reserved/sold status if the deal did not go through — listing is visible in search again.",
    statusReserved: "Reserved",
    statusSold: "Sold",
    statusActive: "Active",
    listingStatusUpdated: "Listing status updated.",
    listingSoldBanner: "This listing is marked as sold.",
    listingReservedBanner: "This listing is reserved.",
    listingSoldNoContact: "This truck is sold — messaging is closed.",
    listingInactiveNoContact:
      "Messaging is not available while this listing is reserved or otherwise unavailable.",
    buyerMessagesTitle: "Buyer messages",
    noBuyerMessages:
      "No messages yet. When a buyer contacts you about a listing, it will appear here.",
    fromBuyer: "From",
    yourMessagesToSellers: "Your messages to sellers",
    yourMessagesToSellersHelp: "Questions you sent about listings — seller replies appear below.",
    noSentMessages: "You have not messaged any sellers yet.",
    sellerReplyLabel: "Seller reply",
    yourReplyLabel: "Your reply",
    replyPlaceholder: "Write your reply to the buyer…",
    sendReply: "Send reply",
    replyEmpty: "Reply cannot be empty.",
    replyFailed: "Could not send reply.",
    replySentSuccess: "Reply sent.",
    yourMessageToSeller: "Your message",
    waitingForSellerReply: "The seller has not replied yet.",
    chatNotificationsTitle: "Messages",
    noChatThreads: "No conversations yet.",
    openAccountMessages: "Account & all chats",
    openChat: "Open chat",
    unreadMessages: "unread",
    chatLoadFailed: "Could not load this chat.",
    chatInvalidThread: "Invalid conversation.",
    chatYouAreSeller: "You are the seller in this chat.",
    chatYouAreBuyer: "You contacted the seller about this listing.",
    viewListing: "View listing",
    chatReplyPlaceholder: "Type a message… (Enter to send, Shift+Enter for new line)",
    sellerPhoneLabel: "Phone number",
    sellerPhoneHelp: "Buyers can use this number to call you about this listing.",
    loginToSendMessage: "Log in to send a message to the seller.",
    sendMessageAction: "Send message",
    messagePlaceholder: "Write your message…",
    messageSentSuccess: "Message sent.",
    messageSendFailed: "Could not send message.",
    ownListingNoMessage: "This is your listing.",
    listingCannotReceiveMessages: "This listing cannot receive messages.",

    // Home Page
    heroTitle: "Find Your Perfect Commercial Truck",
    heroSubtitle: "Browse thousands of quality used and commercial trucks from trusted sellers nationwide",
    browseInventory: "Browse Inventory",
    listYourTruck: "List Your Truck",
    
    // Features
    advancedSearch: "Advanced Search",
    advancedSearchDesc: "Filter by make, model, year, price, mileage and more to find exactly what you need",
    trustedSellers: "Trusted Sellers",
    trustedSellersDesc: "Buy from verified individual sellers and reputable commercial dealerships",
    bestPrices: "Best Prices",
    bestPricesDesc: "Competitive pricing on quality trucks with transparent pricing and detailed specs",
    
    // Featured Section
    featuredTrucks: "Featured Trucks",
    viewAll: "View All",
    loading: "Loading…",
    loadFailed: "Could not load listings. Is the API running?",
    
    // CTA
    readyToSell: "Ready to Sell Your Truck?",
    readyToSellDesc: "List your truck for free and reach thousands of potential buyers. Individual sellers and companies welcome.",
    getStarted: "Get Started",
    
    // Categories
    allTrucks: "All Trucks",
    traditional: "Traditional",
    lightCommercial: "Light Commercial",
    constructionEquipment: "Construction Equipment",
    catTractorhead: "Tractorhead",
    catTruckRigid: "Truck",
    catLightCommercialVehicle: "Light commercial vehicle",
    catConstructionEquipment: "Construction equipment",
    catSemiTrailer: "Semi-trailer",

    // Truck Types
    commercial: "Commercial",
    pickup: "Pickup",
    van: "Van",
    dump: "Dump Truck",
    flatbed: "Flatbed",
    semi: "Semi Truck",
    
    // Inventory Page
    browseInventoryTitle: "Browse Inventory",
    searchPlaceholder: "Search by make, model, or location...",
    sortBy: "Sort by",
    filters: "Filters",
    clear: "Clear",
    clearAllFilters: "Clear All Filters",
    showingResults: "Showing",
    of: "of",
    trucks: "trucks",
    noTrucksFound: "No trucks found matching your criteria",
    
    // Sort Options
    newestFirst: "Newest First",
    priceLowToHigh: "Price: Low to High",
    priceHighToLow: "Price: High to Low",
    yearNewest: "Year: Newest",
    yearOldest: "Year: Oldest",
    mileageLowToHigh: "Mileage: Low to High",
    mileageHighToLow: "Mileage: High to Low",
    
    // Filters
    truckType: "Truck Type",
    condition: "Condition",
    priceRange: "Price Range",
    yearRange: "Year",
    mileageRange: "Mileage",
    transmission: "Transmission",
    fuelType: "Fuel Type",
    sellerType: "Seller Type",
    
    // Condition
    excellent: "Excellent",
    good: "Good",
    fair: "Fair",
    notWorking: "Not Working",
    
    // Transmission
    automatic: "Automatic",
    manual: "Manual",
    
    // Fuel Type
    diesel: "Diesel",
    gasoline: "Gasoline",
    electric: "Electric",
    hybrid: "Hybrid",
    
    // Seller Type
    individual: "Individual",
    company: "Company",
    
    // Truck Card
    miles: "miles",
    listingRef: "Ref.",
    
    // Truck Detail
    back: "Back",
    mileage: "Mileage",
    year: "Year",
    description: "Description",
    features: "Features",
    sellerInformation: "Seller Information",
    callSeller: "Call Seller",
    sendMessage: "Send Message",
    additionalInformation: "Additional Information",
    listed: "Listed",
    type: "Type",
    interestedTitle: "Interested in this truck?",
    interestedDesc: "Contact the seller directly to schedule a viewing or get more information.",
    requestInformation: "Request Information",
    truckNotFound: "Truck not found",
    backToInventory: "Back to Inventory",
    
    // Add Truck Page
    listTruckTitle: "List Your Truck for Sale",
    listTruckDesc: "Fill out the form below to add your truck to our marketplace",
    sellFlowTitle: "Sell your trucks",
    sellFlowQuestion: "What do you want to sell?",
    sellContinue: "Continue",
    changeCategory: "Change category",
    typeLockedHint:
      "Vehicle type is set from your category. You can still type any make or model if it is not in the list.",
    sellCatTractorUnit: "Tractor unit",
    sellCatRigidTruck: "Truck",
    sellCatSemiTrailers: "Semi-trailers",
    sellCatVan: "Van",
    sellCatAgriculture: "Agriculture",
    sellCatMachine: "Machine",
    sellCatVarious: "Various",

    aiCategoryStepHint:
      "Upload a photo of the vehicle and we will suggest the best category (requires server setup).",
    aiCategorySuggestFromPhoto: "Suggest category from photo",
    aiCategorySelectedToast: "Suggested category: {label}",
    aiCategoryUnavailable:
      "AI category detection is not configured on the server (set OPENAI_API_KEY).",
    aiCategoryFailed: "Could not analyze the photo. Try again or pick a category manually.",
    aiCategoryAnalyzing: "Analyzing first photo for category…",
    aiCategorySuggestionTitle: "Category suggestion",
    aiCategorySuggestionBody:
      "This photo looks like {label} (about {percent}% confidence). Apply it or keep your current category.",
    aiCategoryApplySuggestion: "Apply suggestion",
    aiCategoryKeepChoice: "Keep current",
    basicInformation: "Basic Information",
    make: "Make",
    model: "Model",
    selectMakePlaceholder: "Select make…",
    selectModelPlaceholder: "Select model…",
    selectMakeFirstModel: "Select a make first",
    searchMakePlaceholder: "Search makes…",
    searchModelPlaceholder: "Search models…",
    comboboxEmptyMakes: "No makes in inventory — type to add one",
    comboboxEmptyModels: "No models for this make — type to add one",
    selectYearPlaceholder: "Select year…",
    comboboxEmptyYears: "No matching years",
    trailerMakeModelHint:
      "Semi-trailers and trailers are often missing from the brand list. Enter at least a brand or a model/spec (e.g. size, series). You can fill one field and leave the other empty.",
    makeOrModelRequired: "Enter at least a brand or a model.",
    selectModelTrailerPlaceholder: "e.g. series, length, or specs",
    useCustomValue: "Use \"{value}\"",
    price: "Price (Saudi Riyals)",
    location: "Location",
    listingState: "State",
    listingCity: "City",
    selectStatePlaceholder: "Select state…",
    selectCityPlaceholder: "Select city…",
    selectStateFirstCity: "Select state first",
    comboboxEmptyRegions: "No matching states",
    comboboxEmptyCities: "No matching cities",
    truckDetails: "Truck Details",
    companyName: "Company Name",
    yourName: "Your Name",
    descriptionAndFeatures: "Description & Features",
    descriptionPlaceholder: "Optional — add details about your truck…",
    featuresPlaceholder: "e.g., Air Conditioning, Backup Camera, Bluetooth",
    featuresSeparate: "Separate features with commas",
    imageUploadLabel: "Listing photos",
    imageUploadHelp:
      "Up to 10 photos — JPEG, PNG, WebP, or GIF, max 5 MB each. A default image is used if you skip photos.",
    imageUploading: "Uploading…",
    imageUploadFailed: "Could not upload image. Try again.",
    tooManyImages: "You can add at most 10 photos.",
    videoUploadLabel: "Listing video (optional)",
    videoUploadHelp: "MP4, WebM, or MOV — max 80 MB.",
    videoUploading: "Uploading video…",
    videoUploadFailed: "Could not upload video. Try again.",
    removeVideo: "Remove video",
    listTruck: "List Truck",
    cancel: "Cancel",
    
    // Form Validation
    optional: "optional",
    required: "is required",
    yearMin: "Year must be 1970 or later",
    yearMax: "Year cannot be in the future",
    mileageMin: "Mileage must be positive",
    priceMin: "Price must be positive",
    descriptionMin: "Description must be at least 50 characters",
    
    // Toast Messages
    truckAddedSuccess: "Truck listing added successfully!",
    saveFailed: "Could not save listing. Try again.",
    
    // 404 Page
    pageNotFound: "Page Not Found",
    pageNotFoundDesc: "The page you're looking for doesn't exist or has been moved.",
    goBackHome: "Go Back Home",

    // Site footer
    footerColBuy: "Buy",
    footerViewStock: "View stock",
    footerHowToBuy: "How to buy a vehicle",
    footerColSell: "Sell",
    footerStartSelling: "Start selling",
    footerColHelp: "Help",
    footerContact: "Contact",
    footerCareers: "Careers",
    footerColLearn: "Learn",
    footerAbout: "About Trucks",
    footerNews: "News",
    footerEthics: "Ethics",
    footerSubscribeNewsletter: "Subscribe to our newsletter",
    footerPrivacy: "Privacy policy",
    footerCookie: "Cookie policy",
    footerSitemap: "Sitemap",
    footerCopyright: "© Copyright 2026 Trucks",
    footerAnyQuestions: "Any questions?",
    footerDismissQuestionWidget: "Hide",
    footerSocialAria: "Trucks on {network}",
  },
  ar: {
    // Header
    siteName: "شاحنات",
    home: "الرئيسية",
    inventory: "المخزون",
    sellYourTruck: "بيع شاحنتك",
    loginTitle: "تسجيل الدخول",
    loginSubtitle: "سجّل الدخول لإدراج شاحنتك على شاحنات.",
    loginAction: "تسجيل الدخول",
    loginSuccess: "مرحباً بعودتك!",
    loginFailed: "تعذر تسجيل الدخول. تحقق من البريد وكلمة المرور.",
    signupTitle: "إنشاء حساب",
    signupSubtitle: "سجّل حساباً لنشر إعلان شاحنتك.",
    signupAction: "إنشاء حساب",
    signupSuccess: "تم إنشاء الحساب!",
    signupFailed: "تعذر التسجيل. جرّب بريداً آخر.",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    confirmPassword: "تأكيد كلمة المرور",
    firstName: "الاسم الأول",
    lastName: "اسم العائلة",
    mobileNumber: "رقم الجوال",
    accountType: "نوع الحساب",
    accountTypeQuestion: "كيف تريد استخدام شاحنات؟",
    accountTypeIndividual: "فرد",
    accountTypeCompany: "منشأة",
    accountTypeContinue: "متابعة",
    changeAccountType: "تغيير نوع الحساب",
    companyNameRequired: "اسم المنشأة مطلوب.",
    crNumberLabel: "رقم السجل التجاري",
    crNumberPlaceholder: "رقم السجل التجاري (10 أرقام)",
    crNumberInvalid: "أدخل رقم سجل تجاري صحيح مكوّن من 10 أرقام.",
    hasVatLabel: "لدى المنشأة رقم ضريبي (VAT)",
    vatNumberLabel: "الرقم الضريبي",
    vatNumberPlaceholder: "15 رقماً، يبدأ وينتهي بالرقم 3",
    vatNumberInvalid: "أدخل رقماً ضريبياً صحيحاً مكوّناً من 15 رقماً (يبدأ وينتهي بالرقم 3).",
    passwordMismatch: "كلمتا المرور غير متطابقتين.",
    noAccount: "ليس لديك حساب؟",
    haveAccount: "لديك حساب بالفعل؟",
    signUp: "إنشاء حساب",
    logIn: "تسجيل الدخول",
    logout: "تسجيل الخروج",
    signedInAs: "مسجّل دخولك كـ",
    profileAccount: "الحساب",
    profileTitle: "حسابك",
    profileSubtitle: "استفسارات المشترين عن إعلاناتك.",
    accountDetails: "تفاصيل الحساب",
    fullNameLabel: "الاسم",
    yes: "نعم",
    no: "لا",
    companyProfileTitle: "بيانات الشركة",
    companyProfileDesc: "تظهر للمشترين في إعلاناتك وتُستخدم للتواصل معك.",
    registeredCompanyInfo: "بيانات التسجيل",
    companyLogoLabel: "شعار الشركة",
    uploadLogo: "رفع الشعار",
    changeLogo: "تغيير الشعار",
    removeLogo: "إزالة",
    logoUploadFailed: "تعذر رفع الشعار. حاول مرة أخرى.",
    additionalPhonesLabel: "أرقام تواصل إضافية",
    additionalPhonesHelp: "أضف أرقاماً إضافية يمكن للمشترين استخدامها للتواصل مع شركتك (مثل خط المبيعات).",
    addPhoneNumber: "إضافة رقم",
    removeNumber: "إزالة الرقم",
    representativeNameLabel: "المندوب المسؤول — الاسم",
    representativePhoneLabel: "المندوب المسؤول — الجوال",
    saveCompanyProfile: "حفظ بيانات الشركة",
    companyProfileUpdated: "تم تحديث بيانات الشركة.",
    companyProfileUpdateFailed: "تعذر تحديث بيانات الشركة.",
    companyStatusPending: "قيد المراجعة",
    companyStatusApproved: "مفعّل",
    companyStatusRejected: "مرفوض",
    companyStatusPendingHelp:
      "حساب منشأتك بانتظار مراجعة الإدارة. ستتمكن من إدراج المركبات بعد الموافقة عليه.",
    companyStatusRejectedHelp:
      "لم تتم الموافقة على حساب منشأتك. تحقق من بياناتك ووثيقة السجل التجاري، وتواصل مع الدعم إذا كنت تعتقد أن هذا خطأ.",
    crDocumentLabel: "وثيقة السجل التجاري",
    crDocumentHelp: "ارفع نسخة من شهادة السجل التجاري (PDF أو JPG أو PNG أو WebP).",
    crDocumentRequired: "الرجاء إرفاق وثيقة السجل التجاري.",
    uploadCrDocument: "رفع الوثيقة",
    replaceCrDocument: "استبدال الوثيقة",
    viewCrDocument: "عرض الوثيقة",
    noCrDocument: "لم يتم رفع أي وثيقة بعد.",
    crDocumentUploadFailed: "تعذر رفع الوثيقة. حاول مرة أخرى.",
    crDocumentUploadFailedAfterSignup:
      "تم إنشاء الحساب، لكن تعذر رفع الوثيقة. أضفها من صفحة حسابك.",
    termsRequired: "يجب الموافقة على الشروط والأحكام للمتابعة.",
    agreeToTermsPrefix: "أوافق على",
    termsAndConditionsLink: "الشروط والأحكام",
    termsContent:
      "1. قبول الشروط\nبإنشائك حساباً فإنك توافق على استخدام شاحنات بمسؤولية ووفقاً لهذه الشروط.\n\n2. مسؤولية الحساب\nأنت مسؤول عن دقة المعلومات التي تقدمها، بما في ذلك بيانات المنشأة وبيانات التواصل، وعن الحفاظ على سرية بيانات الدخول الخاصة بك.\n\n3. الإعلانات\nيجب أن تكون الإعلانات دقيقة وتصف مركبات تملكها أو مخوّل ببيعها. يحق لـ شاحنات إزالة أي إعلان مضلل أو احتيالي أو يخالف الأنظمة المعمول بها.\n\n4. دور المنصة\nتوفر شاحنات منصة تربط البائعين بالمشترين، وهي ليست طرفاً في أي عملية بيع بين المستخدمين ولا تضمن حالة أو قانونية أو قيمة أي مركبة معروضة.\n\n5. التحقق من المنشآت\nتخضع حسابات المنشآت للمراجعة، بما في ذلك التحقق من وثيقة السجل التجاري، قبل السماح لها بنشر الإعلانات.\n\n6. السلوك المحظور\nلا يجوز استخدام المنصة لأغراض مخالفة للنظام، أو نشر إعلانات احتيالية، أو مضايقة المستخدمين الآخرين.\n\n7. حدود المسؤولية\nلا تتحمل شاحنات مسؤولية أي نزاعات أو خسائر أو أضرار ناتجة عن معاملات بين المستخدمين.\n\n8. التعديلات\nقد يتم تحديث هذه الشروط من وقت لآخر؛ ويُعد استمرارك في استخدام المنصة موافقة على الشروط المحدثة.",
    adminNavLink: "الإدارة",
    adminCompaniesTitle: "حسابات المنشآت",
    adminCompaniesSubtitle: "راجع طلبات تسجيل المنشآت ووافق أو ارفض السماح لها بإدراج المركبات.",
    adminAllCompanies: "الكل",
    adminNoCompanies: "لا توجد حسابات منشآت في هذا العرض.",
    adminLoadFailed: "تعذر تحميل حسابات المنشآت.",
    adminApprove: "موافقة",
    adminReject: "رفض",
    adminStatusUpdated: "تم تحديث الحالة.",
    adminStatusUpdateFailed: "تعذر تحديث الحالة.",
    adminArchiveListing: "أرشفة الإعلان",
    adminDeleteListing: "حذف الإعلان",
    adminConfirmDelete: "حذف هذا الإعلان نهائياً؟ لا يمكن التراجع عن هذا الإجراء.",
    adminConfirmArchive: "أرشفة هذا الإعلان؟ سيتم إخفاؤه من المخزون العام.",
    adminListingDeleted: "تم حذف الإعلان.",
    adminListingDeleteFailed: "تعذر حذف الإعلان.",
    adminListingArchived: "تمت أرشفة الإعلان.",
    adminListingArchiveFailed: "تعذر أرشفة الإعلان.",
    adminContactMessagesNavLink: "الرسائل",
    adminContactMessagesTitle: "رسائل التواصل",
    adminContactMessagesSubtitle: "الرسائل المُرسلة عبر نموذج التواصل في الموقع.",
    adminUnreadMessages: "غير مقروءة",
    adminNoContactMessages: "لا توجد رسائل في هذا العرض.",
    adminMarkRead: "تعليم كمقروءة",
    contactPageTitle: "تواصل معنا",
    contactPageSubtitle: "أرسل لنا رسالة وسيتواصل معك فريقنا.",
    contactNameLabel: "الاسم",
    contactSubjectLabel: "الموضوع",
    contactMessageLabel: "الرسالة",
    contactSubmit: "إرسال الرسالة",
    contactSuccess: "تم إرسال رسالتك. سنتواصل معك قريباً.",
    contactFailed: "تعذر إرسال رسالتك. حاول مرة أخرى.",
    securitySettings: "الأمان",
    changePasswordTitle: "تغيير كلمة المرور",
    currentPasswordLabel: "كلمة المرور الحالية",
    newPasswordLabel: "كلمة المرور الجديدة",
    confirmNewPasswordLabel: "تأكيد كلمة المرور الجديدة",
    savePassword: "تحديث كلمة المرور",
    passwordUpdated: "تم تحديث كلمة المرور.",
    passwordMismatchProfile: "كلمتا المرور الجديدتان غير متطابقتين.",
    passwordMinEight: "يجب أن تكون كلمة المرور 8 أحرف على الأقل.",
    changePhoneTitle: "رقم الجوال",
    changePhoneIntro: "لتغيير الرقم نرسل رمز تحقق إلى رقمك الحالي.",
    phoneChangeNoNumber: "لا يوجد رقم محفوظ. أدخل كلمة مرورك والرقم الذي تريد استخدامه.",
    accountPasswordLabel: "كلمة مرور الحساب",
    sendCode: "إرسال رمز التحقق",
    codeSentToast: "تم إرسال رمز التحقق إلى رقمك.",
    devCodeHint: "وضع التطوير: الرمز هو",
    verificationCodeLabel: "رمز التحقق",
    twoFactorTitle: "مطلوب التحقق",
    twoFactorSubtitle: "أدخل رمز التحقق المُرسل إليك لإكمال تسجيل الدخول.",
    confirmTwoFactor: "تحقق",
    signupVerifyTitle: "تحقق من بريدك الإلكتروني",
    signupVerifySubtitle: "أرسلنا رمز تحقق إلى بريدك الإلكتروني. أدخله أدناه لإكمال إنشاء حسابك.",
    confirmSignupCode: "تحقق وأنشئ الحساب",
    resendCode: "إعادة إرسال الرمز",
    resendCodeIn: "يمكنك إعادة إرسال الرمز خلال",
    signupVerifyFailed: "تعذر التحقق من الرمز. حاول مرة أخرى.",
    newPhoneLabel: "رقم الجوال الجديد",
    confirmPhoneChange: "حفظ الرقم الجديد",
    phoneUpdated: "تم تحديث رقم الجوال.",
    phoneStep2Hint: "أدخل الرمز الذي وصلك ثم رقمك الجديد.",
    manageSecuritySettings: "الأمان",
    hideSecuritySettings: "إخفاء",
    myAdverts: "إعلاناتي",
    myAdvertsTitle: "إعلاناتي",
    myAdvertsSubtitle: "الإعلانات التي نشرتها — افتحها أو عدّلها.",
    myAdvertsEmpty: "لم تنشر أي إعلانات بعد.",
    editListing: "تعديل الإعلان",
    editListingTitle: "تعديل الإعلان",
    editListingDesc: "حدّث تفاصيل إعلانك والصور. احفظ عند الانتهاء.",
    listingUpdatedSuccess: "تم تحديث الإعلان.",
    editNotOwner: "يمكنك تعديل إعلاناتك فقط.",
    saveListing: "حفظ التغييرات",
    btnReserved: "محجوز",
    btnSold: "مباع",
    btnBackToActive: "العودة للنشط",
    btnBackToActiveHelp:
      "إلغاء حالة المحجوز/المباع إذا لم يكتمل البيع — يظهر الإعلان في البحث مرة أخرى.",
    statusReserved: "محجوز",
    statusSold: "مباع",
    statusActive: "نشط",
    listingStatusUpdated: "تم تحديث حالة الإعلان.",
    listingSoldBanner: "هذا الإعلان مُعلَم كمباع.",
    listingReservedBanner: "هذا الإعلان محجوز.",
    listingSoldNoContact: "هذه الشاحنة مباعة — إرسال الرسائل غير متاح.",
    listingInactiveNoContact:
      "الرسائل غير متاحة بينما الإعلان محجوز أو غير متاح للبيع.",
    buyerMessagesTitle: "رسائل المشترين",
    noBuyerMessages: "لا توجد رسائل بعد. عندما يتواصل مشترٍ معك سيظهر هنا.",
    fromBuyer: "من",
    yourMessagesToSellers: "رسائلك إلى البائعين",
    yourMessagesToSellersHelp: "الأسئلة التي أرسلتها عن الإعلانات — يظهر رد البائع أدناه.",
    noSentMessages: "لم ترسل أي رسائل بعد.",
    sellerReplyLabel: "رد البائع",
    yourReplyLabel: "ردك",
    replyPlaceholder: "اكتب ردك للمشتري…",
    sendReply: "إرسال الرد",
    replyEmpty: "الرد لا يمكن أن يكون فارغاً.",
    replyFailed: "تعذر إرسال الرد.",
    replySentSuccess: "تم إرسال الرد.",
    yourMessageToSeller: "رسالتك",
    waitingForSellerReply: "لم يرد البائع بعد.",
    chatNotificationsTitle: "الرسائل",
    noChatThreads: "لا محادثات بعد.",
    openAccountMessages: "الحساب وجميع المحادثات",
    openChat: "فتح المحادثة",
    unreadMessages: "غير مقروء",
    chatLoadFailed: "تعذر تحميل المحادثة.",
    chatInvalidThread: "محادثة غير صالحة.",
    chatYouAreSeller: "أنت البائع في هذه المحادثة.",
    chatYouAreBuyer: "تواصلت مع البائع عن هذا الإعلان.",
    viewListing: "عرض الإعلان",
    chatReplyPlaceholder: "اكتب رسالة… (Enter للإرسال، Shift+Enter سطر جديد)",
    sellerPhoneLabel: "رقم الهاتف",
    sellerPhoneHelp: "يمكن للمشترين الاتصال بك على هذا الرقم بخصوص هذا الإعلان.",
    loginToSendMessage: "سجّل الدخول لإرسال رسالة إلى البائع.",
    sendMessageAction: "إرسال الرسالة",
    messagePlaceholder: "اكتب رسالتك…",
    messageSentSuccess: "تم إرسال الرسالة.",
    messageSendFailed: "تعذر إرسال الرسالة.",
    ownListingNoMessage: "هذا إعلانك.",
    listingCannotReceiveMessages: "لا يمكن استقبال رسائل لهذا الإعلان.",

    // Home Page
    heroTitle: "اعثر على شاحنتك التجارية المثالية",
    heroSubtitle: "تصفح آلاف الشاحنات المستعملة والتجارية عالية الجودة من بائعين موثوقين في جميع أنحاء البلاد",
    browseInventory: "تصفح المركبات",
    listYourTruck: "أضف إعلان",
    
    // Features
    advancedSearch: "بحث متقدم",
    advancedSearchDesc: "قم بالتصفية حسب العلامة التجارية والطراز والسنة والسعر والمسافة المقطوعة والمزيد للعثور على ما تحتاجه بالضبط",
    trustedSellers: "بائعون موثوقون",
    trustedSellersDesc: "اشترِ من بائعين أفراد معتمدين ووكلاء تجاريين موثوقين",
    bestPrices: "أفضل الأسعار",
    bestPricesDesc: "أسعار تنافسية على شاحنات عالية الجودة مع تسعير شفاف ومواصفات مفصلة",
    
    // Featured Section
    featuredTrucks: "شاحنات مميزة",
    viewAll: "عرض الكل",
    loading: "جاري التحميل…",
    loadFailed: "تعذر تحميل القوائم. هل واجهة البرمجة تعمل؟",
    
    // CTA
    readyToSell: "هل أنت مستعد لبيع شاحنتك؟",
    readyToSellDesc: "أدرج شاحنتك مجانًا وتواصل مع آلاف المشترين المحتملين. الأفراد والشركات مرحب بهم.",
    getStarted: "ابدأ الآن",
    
    // Categories
    allTrucks: "جميع الشاحنات",
    traditional: "تقليدية",
    lightCommercial: "مركبة تجارية خفيفة",
    constructionEquipment: "معدات بناء",
    catTractorhead: "رأس مقطورة",
    catTruckRigid: "شاحنة",
    catLightCommercialVehicle: "مركبة تجارية خفيفة",
    catConstructionEquipment: "معدات إنشاءات",
    catSemiTrailer: "مقطورة نصفية",

    // Truck Types
    commercial: "تجارية",
    pickup: "بيك أب",
    van: "فان",
    dump: "قلاب",
    flatbed: "سرير مسطح",
    semi: "شاحنة نصفية",
    
    // Inventory Page
    browseInventoryTitle: "تصفح المركبات",
    searchPlaceholder: "البحث حسب العلامة التجارية أو الطراز أو الموقع...",
    sortBy: "ترتيب حسب",
    filters: "الفلاتر",
    clear: "مسح",
    clearAllFilters: "مسح جميع الفلاتر",
    showingResults: "عرض",
    of: "من",
    trucks: "شاحنات",
    noTrucksFound: "لم يتم العثور على شاحنات تطابق معاييرك",
    
    // Sort Options
    newestFirst: "الأحدث أولاً",
    priceLowToHigh: "السعر: من الأقل إلى الأعلى",
    priceHighToLow: "السعر: من الأعلى إلى الأقل",
    yearNewest: "السنة: الأحدث",
    yearOldest: "السنة: الأقدم",
    mileageLowToHigh: "المسافة: من الأقل إلى الأعلى",
    mileageHighToLow: "المسافة: من الأعلى إلى الأقل",
    
    // Filters
    truckType: "نوع الشاحنة",
    condition: "الحالة",
    priceRange: "نطاق السعر",
    yearRange: "السنة",
    mileageRange: "المسافة المقطوعة",
    transmission: "ناقل الحركة",
    fuelType: "نوع الوقود",
    sellerType: "نوع البائع",
    
    // Condition
    excellent: "ممتاز",
    good: "جيد",
    fair: "مقبول",
    notWorking: "لا تعمل",
    
    // Transmission
    automatic: "أوتوماتيك",
    manual: "يدوي",
    
    // Fuel Type
    diesel: "ديزل",
    gasoline: "بنزين",
    electric: "كهربائي",
    hybrid: "هجين",
    
    // Seller Type
    individual: "فرد",
    company: "شركة",
    
    // Truck Card
    miles: "ميل",
    listingRef: "المرجع",
    
    // Truck Detail
    back: "رجوع",
    mileage: "المسافة المقطوعة",
    year: "السنة",
    description: "الوصف",
    features: "المميزات",
    sellerInformation: "معلومات البائع",
    callSeller: "اتصل بالبائع",
    sendMessage: "إرسال رسالة",
    additionalInformation: "معلومات إضافية",
    listed: "تاريخ الإدراج",
    type: "النوع",
    interestedTitle: "مهتم بهذه الشاحنة؟",
    interestedDesc: "اتصل بالبائع مباشرة لجدولة معاينة أو الحصول على مزيد من المعلومات.",
    requestInformation: "طلب معلومات",
    truckNotFound: "الشاحنة غير موجودة",
    backToInventory: "العودة إلى المخزون",
    
    // Add Truck Page
    listTruckTitle: "أدرج شاحنتك للبيع",
    listTruckDesc: "املأ النموذج أدناه لإضافة شاحنتك إلى سوقنا",
    sellFlowTitle: "بيع شاحناتك",
    sellFlowQuestion: "ماذا تريد بيعه؟",
    sellContinue: "متابعة",
    changeCategory: "تغيير الفئة",
    typeLockedHint:
      "نوع المركبة مضبوط حسب الفئة التي اخترتها. يمكنك كتابة أي صانع أو طراز إذا لم يظهر في القائمة.",
    sellCatTractorUnit: "رأس مقطورة",
    sellCatRigidTruck: "شاحنة",
    sellCatSemiTrailers: "نصف مقطورة",
    sellCatVan: "فان",
    sellCatAgriculture: "زراعية",
    sellCatMachine: "آلة / معدات",
    sellCatVarious: "متنوع",

    aiCategoryStepHint:
      "ارفع صورة للمركبة وسنقترح أفضل فئة (يتطلب إعداد الخادم).",
    aiCategorySuggestFromPhoto: "اقتراح الفئة من الصورة",
    aiCategorySelectedToast: "الفئة المقترحة: {label}",
    aiCategoryUnavailable:
      "لم يُضبط كشف الفئة بالذكاء الاصطناعي على الخادم (OPENAI_API_KEY).",
    aiCategoryFailed: "تعذر تحليل الصورة. أعد المحاولة أو اختر الفئة يدوياً.",
    aiCategoryAnalyzing: "جاري تحليل الصورة الأولى للفئة…",
    aiCategorySuggestionTitle: "اقتراح الفئة",
    aiCategorySuggestionBody:
      "تبدو الصورة كـ {label} (حوالي {percent}٪ ثقة). طبّق الاقتراح أو أبقِ فئتك الحالية.",
    aiCategoryApplySuggestion: "تطبيق الاقتراح",
    aiCategoryKeepChoice: "الإبقاء على الحالي",
    basicInformation: "معلومات أساسية",
    make: "العلامة التجارية",
    model: "الطراز",
    selectMakePlaceholder: "اختر الصانع…",
    selectModelPlaceholder: "اختر الطراز…",
    selectMakeFirstModel: "اختر الصانع أولاً",
    searchMakePlaceholder: "ابحث عن الصانع…",
    searchModelPlaceholder: "ابحث عن الطراز…",
    comboboxEmptyMakes: "لا توجد علامات في المخزون — اكتب لإضافة واحدة",
    comboboxEmptyModels: "لا توجد طرازات لهذا الصانع — اكتب لإضافة واحد",
    selectYearPlaceholder: "اختر السنة…",
    comboboxEmptyYears: "لا توجد سنوات مطابقة",
    trailerMakeModelHint:
      "نصف المقطورات والمقطورات غالباً لا تظهر أسماء العلامات في القائمة. أدخل على الأقل العلامة أو الطراز/المواصفات (مثل الطول أو السلسلة). يمكنك ملء حقل واحد وترك الآخر فارغاً.",
    makeOrModelRequired: "أدخل العلامة أو الطراز على الأقل.",
    selectModelTrailerPlaceholder: "مثلاً: السلسلة، الطول، أو المواصفات",
    useCustomValue: "استخدم \"{value}\"",
    price: "السعر (ريال سعودي)",
    location: "الموقع",
    listingState: "المنطقة",
    listingCity: "المدينة",
    selectStatePlaceholder: "اختر المنطقة…",
    selectCityPlaceholder: "اختر المدينة…",
    selectStateFirstCity: "اختر المنطقة أولاً",
    comboboxEmptyRegions: "لا توجد مناطق مطابقة",
    comboboxEmptyCities: "لا توجد مدن مطابقة",
    truckDetails: "تفاصيل الشاحنة",
    companyName: "اسم الشركة",
    yourName: "اسمك",
    descriptionAndFeatures: "الوصف والمميزات",
    descriptionPlaceholder: "اختياري — أضف تفاصيل عن شاحنتك…",
    featuresPlaceholder: "مثل: تكييف الهواء، كاميرا خلفية، بلوتوث",
    featuresSeparate: "افصل المميزات بفواصل",
    imageUploadLabel: "صور الإعلان",
    imageUploadHelp:
      "حتى 10 صور — JPEG أو PNG أو WebP أو GIF، بحد أقصى 5 ميجابايت لكل صورة. تُستخدم صورة افتراضية إذا لم ترفع صوراً.",
    imageUploading: "جاري الرفع…",
    imageUploadFailed: "تعذر رفع الصورة. حاول مرة أخرى.",
    tooManyImages: "يمكنك إضافة 10 صور كحد أقصى.",
    videoUploadLabel: "فيديو الإعلان (اختياري)",
    videoUploadHelp: "MP4 أو WebM أو MOV — بحد أقصى 80 ميجابايت.",
    videoUploading: "جاري رفع الفيديو…",
    videoUploadFailed: "تعذر رفع الفيديو. حاول مرة أخرى.",
    removeVideo: "إزالة الفيديو",
    listTruck: "إدراج الشاحنة",
    cancel: "إلغاء",
    
    // Form Validation
    optional: "اختياري",
    required: "مطلوب",
    yearMin: "يجب أن تكون السنة 1970 أو أحدث",
    yearMax: "لا يمكن أن تكون السنة في المستقبل",
    mileageMin: "يجب أن تكون المسافة المقطوعة موجبة",
    priceMin: "يجب أن يكون السعر موجبًا",
    descriptionMin: "يجب أن يكون الوصف 50 حرفًا على الأقل",
    
    // Toast Messages
    truckAddedSuccess: "تمت إضافة إعلان الشاحنة بنجاح!",
    saveFailed: "تعذر حفظ الإعلان. حاول مرة أخرى.",
    
    // 404 Page
    pageNotFound: "الصفحة غير موجودة",
    pageNotFoundDesc: "الصفحة التي تبحث عنها غير موجودة أو تم نقلها.",
    goBackHome: "العودة إلى الصفحة الرئيسية",

    // Site footer
    footerColBuy: "الشراء",
    footerViewStock: "عرض المخزون",
    footerHowToBuy: "كيفية شراء مركبة",
    footerColSell: "البيع",
    footerStartSelling: "ابدأ البيع",
    footerColHelp: "المساعدة",
    footerContact: "اتصل بنا",
    footerCareers: "الوظائف",
    footerColLearn: "تعرّف",
    footerAbout: "عن شاحنات",
    footerNews: "الأخبار",
    footerEthics: "الأخلاقيات",
    footerSubscribeNewsletter: "اشترك في النشرة الإخبارية",
    footerPrivacy: "سياسة الخصوصية",
    footerCookie: "سياسة ملفات تعريف الارتباط",
    footerSitemap: "خريطة الموقع",
    footerCopyright: "© حقوق النشر 2026 شاحنات",
    footerAnyQuestions: "أي أسئلة؟",
    footerDismissQuestionWidget: "إخفاء",
    footerSocialAria: "شاحنات على {network}",
  },
  ur: {
    // Header
    siteName: "Trucks",
    home: "ہوم",
    inventory: "انوینٹری",
    sellYourTruck: "اپنا ٹرک بیچیں",
    loginTitle: "لاگ ان کریں",
    loginSubtitle: "اپنا ٹرک Trucks پر درج کرنے کے لیے سائن ان کریں۔",
    loginAction: "لاگ ان کریں",
    loginSuccess: "خوش آمدید!",
    loginFailed: "لاگ ان نہیں ہو سکا۔ اپنا ای میل اور پاس ورڈ چیک کریں۔",
    signupTitle: "اکاؤنٹ بنائیں",
    signupSubtitle: "اپنا ٹرک درج کرنے کے لیے سائن اپ کریں۔",
    signupAction: "سائن اپ کریں",
    signupSuccess: "اکاؤنٹ بن گیا!",
    signupFailed: "سائن اپ نہیں ہو سکا۔ دوسرا ای میل آزمائیں۔",
    email: "ای میل",
    password: "پاس ورڈ",
    confirmPassword: "پاس ورڈ کی تصدیق کریں",
    firstName: "پہلا نام",
    lastName: "آخری نام",
    mobileNumber: "موبائل نمبر",
    accountType: "اکاؤنٹ کی قسم",
    accountTypeQuestion: "آپ Trucks کیسے استعمال کریں گے؟",
    accountTypeIndividual: "فرد",
    accountTypeCompany: "کمپنی / ادارہ",
    accountTypeContinue: "جاری رکھیں",
    changeAccountType: "اکاؤنٹ کی قسم تبدیل کریں",
    companyNameRequired: "کمپنی کا نام درکار ہے۔",
    crNumberLabel: "کمرشل رجسٹریشن نمبر (CR)",
    crNumberPlaceholder: "10 ہندسوں کا CR نمبر",
    crNumberInvalid: "براہ کرم 10 ہندسوں کا درست کمرشل رجسٹریشن نمبر درج کریں۔",
    hasVatLabel: "اس ادارے کے پاس VAT نمبر ہے",
    vatNumberLabel: "VAT نمبر",
    vatNumberPlaceholder: "15 ہندسے، 3 سے شروع اور 3 پر ختم",
    vatNumberInvalid: "براہ کرم 15 ہندسوں کا درست VAT نمبر درج کریں (3 سے شروع اور 3 پر ختم)۔",
    passwordMismatch: "پاس ورڈز مماثل نہیں ہیں۔",
    noAccount: "اکاؤنٹ نہیں ہے؟",
    haveAccount: "پہلے سے اکاؤنٹ ہے؟",
    signUp: "سائن اپ کریں",
    logIn: "لاگ ان کریں",
    logout: "لاگ آؤٹ",
    signedInAs: "بطور سائن ان",
    profileAccount: "اکاؤنٹ",
    profileTitle: "آپ کا اکاؤنٹ",
    profileSubtitle: "آپ کے اشتہارات کے بارے میں خریداروں کے سوالات۔",
    accountDetails: "اکاؤنٹ کی تفصیلات",
    fullNameLabel: "نام",
    yes: "ہاں",
    no: "نہیں",
    companyProfileTitle: "کمپنی پروفائل",
    companyProfileDesc: "یہ خریداروں کو آپ کے اشتہارات میں دکھایا جاتا ہے اور آپ سے رابطے کے لیے استعمال ہوتا ہے۔",
    registeredCompanyInfo: "رجسٹرڈ کمپنی کی معلومات",
    companyLogoLabel: "کمپنی کا لوگو",
    uploadLogo: "لوگو اپ لوڈ کریں",
    changeLogo: "لوگو تبدیل کریں",
    removeLogo: "ہٹائیں",
    logoUploadFailed: "لوگو اپ لوڈ نہیں ہو سکا۔ دوبارہ کوشش کریں۔",
    additionalPhonesLabel: "اضافی رابطہ نمبرز",
    additionalPhonesHelp: "اضافی نمبرز شامل کریں جو خریدار آپ کی کمپنی سے رابطے کے لیے استعمال کر سکیں (مثلاً سیلز لائن)۔",
    addPhoneNumber: "نمبر شامل کریں",
    removeNumber: "نمبر ہٹائیں",
    representativeNameLabel: "ذمہ دار نمائندہ — نام",
    representativePhoneLabel: "ذمہ دار نمائندہ — فون",
    saveCompanyProfile: "کمپنی پروفائل محفوظ کریں",
    companyProfileUpdated: "کمپنی پروفائل اپ ڈیٹ ہو گئی۔",
    companyProfileUpdateFailed: "کمپنی پروفائل اپ ڈیٹ نہیں ہو سکی۔",
    companyStatusPending: "جائزہ زیر التوا",
    companyStatusApproved: "منظور شدہ",
    companyStatusRejected: "مسترد شدہ",
    companyStatusPendingHelp:
      "آپ کے کمپنی اکاؤنٹ کا ایڈمن جائزہ باقی ہے۔ منظوری کے بعد آپ گاڑیاں درج کر سکیں گے۔",
    companyStatusRejectedHelp:
      "آپ کے کمپنی اکاؤنٹ کو منظور نہیں کیا گیا۔ اپنی تفصیلات اور کمرشل رجسٹریشن دستاویز چیک کریں، پھر اگر آپ کو لگے کہ یہ غلطی ہے تو سپورٹ سے رابطہ کریں۔",
    crDocumentLabel: "کمرشل رجسٹریشن دستاویز",
    crDocumentHelp: "اپنے کمرشل رجسٹریشن سرٹیفکیٹ کی کاپی اپ لوڈ کریں (PDF، JPG، PNG، یا WebP)۔",
    crDocumentRequired: "براہ کرم اپنی کمرشل رجسٹریشن دستاویز منسلک کریں۔",
    uploadCrDocument: "دستاویز اپ لوڈ کریں",
    replaceCrDocument: "دستاویز تبدیل کریں",
    viewCrDocument: "دستاویز دیکھیں",
    noCrDocument: "ابھی تک کوئی دستاویز اپ لوڈ نہیں کی گئی۔",
    crDocumentUploadFailed: "دستاویز اپ لوڈ نہیں ہو سکی۔ دوبارہ کوشش کریں۔",
    crDocumentUploadFailedAfterSignup:
      "اکاؤنٹ بن گیا، لیکن دستاویز اپ لوڈ نہیں ہو سکی۔ اسے اپنے اکاؤنٹ پیج سے شامل کریں۔",
    termsRequired: "جاری رکھنے کے لیے آپ کو شرائط و ضوابط سے اتفاق کرنا ہوگا۔",
    agreeToTermsPrefix: "میں اتفاق کرتا ہوں",
    termsAndConditionsLink: "شرائط و ضوابط",
    termsContent:
      "1۔ شرائط کی منظوری\nاکاؤنٹ بنا کر آپ اتفاق کرتے ہیں کہ آپ Trucks کو ذمہ داری سے اور ان شرائط کے مطابق استعمال کریں گے۔\n\n2۔ اکاؤنٹ کی ذمہ داری\nآپ اپنی فراہم کردہ معلومات کی درستگی کے ذمہ دار ہیں، بشمول کمپنی اور رابطے کی تفصیلات، اور اپنے لاگ ان کی معلومات کو محفوظ رکھنے کے بھی۔\n\n3۔ اشتہارات\nاشتہارات درست ہونے چاہئیں اور ایسی گاڑیوں کو بیان کریں جن کے آپ مالک ہیں یا جنہیں بیچنے کا آپ کو اختیار ہے۔ Trucks ایسے اشتہارات ہٹا سکتا ہے جو گمراہ کن، دھوکہ دہی پر مبنی ہوں یا قانون کی خلاف ورزی کرتے ہوں۔\n\n4۔ مارکیٹ پلیس کا کردار\nTrucks خریداروں اور بیچنے والوں کو ملانے کے لیے ایک پلیٹ فارم فراہم کرتا ہے۔ Trucks صارفین کے درمیان کسی بھی سودے کا فریق نہیں ہے اور کسی بھی درج شدہ گاڑی کی حالت، قانونی حیثیت یا قیمت کی ضمانت نہیں دیتا۔\n\n5۔ کمپنی کی تصدیق\nکمپنی اکاؤنٹس جائزے کے تابع ہیں، بشمول کمرشل رجسٹریشن دستاویز کی تصدیق، اس سے پہلے کہ وہ اشتہارات شائع کر سکیں۔\n\n6۔ ممنوعہ رویہ\nآپ پلیٹ فارم کو غیر قانونی مقاصد کے لیے، دھوکہ دہی پر مبنی اشتہارات پوسٹ کرنے کے لیے، یا دوسرے صارفین کو ہراساں کرنے کے لیے استعمال نہیں کر سکتے۔\n\n7۔ ذمہ داری کی حد\nصارفین کے درمیان لین دین سے پیدا ہونے والے تنازعات، نقصانات یا خسارے کا Trucks ذمہ دار نہیں ہے۔\n\n8۔ تبدیلیاں\nیہ شرائط وقتاً فوقتاً اپ ڈیٹ کی جا سکتی ہیں؛ پلیٹ فارم کا استعمال جاری رکھنا اپ ڈیٹ شدہ شرائط کی منظوری تصور ہوگا۔",
    adminNavLink: "ایڈمن",
    adminCompaniesTitle: "کمپنی اکاؤنٹس",
    adminCompaniesSubtitle: "کمپنی سائن اپس کا جائزہ لیں اور گاڑیاں درج کرنے کی اجازت منظور یا مسترد کریں۔",
    adminAllCompanies: "تمام",
    adminNoCompanies: "اس ویو میں کوئی کمپنی اکاؤنٹ نہیں ہے۔",
    adminLoadFailed: "کمپنی اکاؤنٹس لوڈ نہیں ہو سکے۔",
    adminApprove: "منظور کریں",
    adminReject: "مسترد کریں",
    adminStatusUpdated: "حیثیت اپ ڈیٹ ہو گئی۔",
    adminStatusUpdateFailed: "حیثیت اپ ڈیٹ نہیں ہو سکی۔",
    adminArchiveListing: "اشتہار آرکائیو کریں",
    adminDeleteListing: "اشتہار حذف کریں",
    adminConfirmDelete: "کیا اس اشتہار کو مستقل طور پر حذف کرنا ہے؟ یہ واپس نہیں ہو سکتا۔",
    adminConfirmArchive: "کیا اس اشتہار کو آرکائیو کرنا ہے؟ یہ عوامی انوینٹری سے چھپ جائے گا۔",
    adminListingDeleted: "اشتہار حذف ہو گیا۔",
    adminListingDeleteFailed: "اشتہار حذف نہیں ہو سکا۔",
    adminListingArchived: "اشتہار آرکائیو ہو گیا۔",
    adminListingArchiveFailed: "اشتہار آرکائیو نہیں ہو سکا۔",
    adminContactMessagesNavLink: "پیغامات",
    adminContactMessagesTitle: "رابطہ پیغامات",
    adminContactMessagesSubtitle: "سائٹ کے رابطہ فارم کے ذریعے بھیجے گئے پیغامات۔",
    adminUnreadMessages: "غیر پڑھا",
    adminNoContactMessages: "اس ویو میں کوئی پیغام نہیں۔",
    adminMarkRead: "پڑھا گیا نشان زد کریں",
    contactPageTitle: "ہم سے رابطہ کریں",
    contactPageSubtitle: "ہمیں پیغام بھیجیں اور ہماری ٹیم آپ سے رابطہ کرے گی۔",
    contactNameLabel: "نام",
    contactSubjectLabel: "موضوع",
    contactMessageLabel: "پیغام",
    contactSubmit: "پیغام بھیجیں",
    contactSuccess: "آپ کا پیغام بھیج دیا گیا ہے۔ ہم جلد آپ سے رابطہ کریں گے۔",
    contactFailed: "آپ کا پیغام نہیں بھیجا جا سکا۔ دوبارہ کوشش کریں۔",
    securitySettings: "سیکیورٹی",
    changePasswordTitle: "پاس ورڈ تبدیل کریں",
    currentPasswordLabel: "موجودہ پاس ورڈ",
    newPasswordLabel: "نیا پاس ورڈ",
    confirmNewPasswordLabel: "نئے پاس ورڈ کی تصدیق کریں",
    savePassword: "پاس ورڈ اپ ڈیٹ کریں",
    passwordUpdated: "پاس ورڈ اپ ڈیٹ ہو گیا۔",
    passwordMismatchProfile: "نئے پاس ورڈز مماثل نہیں ہیں۔",
    passwordMinEight: "پاس ورڈ کم از کم 8 حروف کا ہونا چاہیے۔",
    changePhoneTitle: "موبائل نمبر",
    changePhoneIntro:
      "نمبر تبدیل کرنے کے لیے، ہم آپ کے موجودہ نمبر پر تصدیقی کوڈ بھیجتے ہیں۔",
    phoneChangeNoNumber: "کوئی نمبر درج نہیں ہے۔ اپنا پاس ورڈ اور وہ نمبر درج کریں جو آپ استعمال کرنا چاہتے ہیں۔",
    accountPasswordLabel: "اکاؤنٹ کا پاس ورڈ",
    sendCode: "تصدیقی کوڈ بھیجیں",
    codeSentToast: "آپ کے نمبر پر تصدیقی کوڈ بھیج دیا گیا ہے۔",
    devCodeHint: "ڈویلپمنٹ: آپ کا کوڈ ہے",
    verificationCodeLabel: "تصدیقی کوڈ",
    twoFactorTitle: "تصدیق درکار ہے",
    twoFactorSubtitle: "لاگ ان مکمل کرنے کے لیے آپ کو بھیجا گیا تصدیقی کوڈ درج کریں۔",
    confirmTwoFactor: "تصدیق کریں",
    signupVerifyTitle: "اپنی ای میل کی تصدیق کریں",
    signupVerifySubtitle: "ہم نے آپ کی ای میل پر ایک تصدیقی کوڈ بھیجا ہے۔ اپنا اکاؤنٹ مکمل کرنے کے لیے اسے نیچے درج کریں۔",
    confirmSignupCode: "تصدیق کریں اور اکاؤنٹ بنائیں",
    resendCode: "کوڈ دوبارہ بھیجیں",
    resendCodeIn: "کوڈ دوبارہ بھیجیں",
    signupVerifyFailed: "کوڈ کی تصدیق نہیں ہو سکی۔ دوبارہ کوشش کریں۔",
    newPhoneLabel: "نیا موبائل نمبر",
    confirmPhoneChange: "نیا نمبر محفوظ کریں",
    phoneUpdated: "موبائل نمبر اپ ڈیٹ ہو گیا۔",
    phoneStep2Hint: "آپ کو موصول ہونے والا کوڈ درج کریں، پھر اپنا نیا نمبر۔",
    manageSecuritySettings: "سیکیورٹی",
    hideSecuritySettings: "چھپائیں",
    myAdverts: "میرے اشتہارات",
    myAdvertsTitle: "میرے اشتہارات",
    myAdvertsSubtitle: "آپ کے شائع کردہ اشتہارات — ان میں سے کسی کو بھی کھولیں یا ترمیم کریں۔",
    myAdvertsEmpty: "آپ نے ابھی تک کوئی ٹرک درج نہیں کیا۔",
    editListing: "اشتہار میں ترمیم کریں",
    editListingTitle: "اشتہار میں ترمیم کریں",
    editListingDesc: "اپنے اشتہار کی تفصیلات اور تصاویر اپ ڈیٹ کریں۔ مکمل ہونے پر محفوظ کریں۔",
    listingUpdatedSuccess: "اشتہار اپ ڈیٹ ہو گیا۔",
    editNotOwner: "آپ صرف اپنے اشتہارات میں ترمیم کر سکتے ہیں۔",
    saveListing: "تبدیلیاں محفوظ کریں",
    btnReserved: "مخصوص",
    btnSold: "فروخت شدہ",
    btnBackToActive: "دوبارہ فعال کریں",
    btnBackToActiveHelp:
      "اگر سودا مکمل نہیں ہوا تو مخصوص/فروخت شدہ حیثیت منسوخ کریں — اشتہار دوبارہ تلاش میں نظر آئے گا۔",
    statusReserved: "مخصوص",
    statusSold: "فروخت شدہ",
    statusActive: "فعال",
    listingStatusUpdated: "اشتہار کی حیثیت اپ ڈیٹ ہو گئی۔",
    listingSoldBanner: "یہ اشتہار فروخت شدہ کے طور پر نشان زد ہے۔",
    listingReservedBanner: "یہ اشتہار مخصوص ہے۔",
    listingSoldNoContact: "یہ ٹرک فروخت ہو چکا ہے — پیغام رسانی بند ہے۔",
    listingInactiveNoContact:
      "جب تک یہ اشتہار مخصوص یا دستیاب نہیں ہے، پیغام رسانی دستیاب نہیں ہے۔",
    buyerMessagesTitle: "خریداروں کے پیغامات",
    noBuyerMessages: "ابھی تک کوئی پیغام نہیں۔ جب کوئی خریدار آپ کے اشتہار کے بارے میں رابطہ کرے گا، یہ یہاں ظاہر ہوگا۔",
    fromBuyer: "از",
    yourMessagesToSellers: "بیچنے والوں کو آپ کے پیغامات",
    yourMessagesToSellersHelp: "آپ نے اشتہارات کے بارے میں بھیجے گئے سوالات — بیچنے والے کے جوابات نیچے ظاہر ہوں گے۔",
    noSentMessages: "آپ نے ابھی تک کسی بیچنے والے کو پیغام نہیں بھیجا۔",
    sellerReplyLabel: "بیچنے والے کا جواب",
    yourReplyLabel: "آپ کا جواب",
    replyPlaceholder: "خریدار کو اپنا جواب لکھیں…",
    sendReply: "جواب بھیجیں",
    replyEmpty: "جواب خالی نہیں ہو سکتا۔",
    replyFailed: "جواب بھیجا نہیں جا سکا۔",
    replySentSuccess: "جواب بھیج دیا گیا۔",
    yourMessageToSeller: "آپ کا پیغام",
    waitingForSellerReply: "بیچنے والے نے ابھی تک جواب نہیں دیا۔",
    chatNotificationsTitle: "پیغامات",
    noChatThreads: "ابھی تک کوئی گفتگو نہیں۔",
    openAccountMessages: "اکاؤنٹ اور تمام چیٹس",
    openChat: "چیٹ کھولیں",
    unreadMessages: "غیر پڑھا",
    chatLoadFailed: "یہ چیٹ لوڈ نہیں ہو سکی۔",
    chatInvalidThread: "غلط گفتگو۔",
    chatYouAreSeller: "اس چیٹ میں آپ بیچنے والے ہیں۔",
    chatYouAreBuyer: "آپ نے اس اشتہار کے بارے میں بیچنے والے سے رابطہ کیا۔",
    viewListing: "اشتہار دیکھیں",
    chatReplyPlaceholder: "پیغام لکھیں… (بھیجنے کے لیے Enter، نئی لائن کے لیے Shift+Enter)",
    sellerPhoneLabel: "فون نمبر",
    sellerPhoneHelp: "خریدار اس اشتہار کے بارے میں آپ کو کال کرنے کے لیے یہ نمبر استعمال کر سکتے ہیں۔",
    loginToSendMessage: "بیچنے والے کو پیغام بھیجنے کے لیے لاگ ان کریں۔",
    sendMessageAction: "پیغام بھیجیں",
    messagePlaceholder: "اپنا پیغام لکھیں…",
    messageSentSuccess: "پیغام بھیج دیا گیا۔",
    messageSendFailed: "پیغام نہیں بھیجا جا سکا۔",
    ownListingNoMessage: "یہ آپ کا اشتہار ہے۔",
    listingCannotReceiveMessages: "اس اشتہار پر پیغامات موصول نہیں ہو سکتے۔",

    // Home Page
    heroTitle: "اپنا بہترین کمرشل ٹرک تلاش کریں",
    heroSubtitle: "ملک بھر کے قابلِ اعتماد بیچنے والوں سے ہزاروں معیاری استعمال شدہ اور کمرشل ٹرکس براؤز کریں",
    browseInventory: "انوینٹری براؤز کریں",
    listYourTruck: "اپنا ٹرک درج کریں",

    // Features
    advancedSearch: "ایڈوانسڈ سرچ",
    advancedSearchDesc: "بالکل وہی چیز تلاش کرنے کے لیے میک، ماڈل، سال، قیمت، مائلیج اور مزید کے ذریعے فلٹر کریں",
    trustedSellers: "قابلِ اعتماد بیچنے والے",
    trustedSellersDesc: "تصدیق شدہ انفرادی بیچنے والوں اور معتبر کمرشل ڈیلرشپس سے خریدیں",
    bestPrices: "بہترین قیمتیں",
    bestPricesDesc: "شفاف قیمتوں اور تفصیلی خصوصیات کے ساتھ معیاری ٹرکس پر مسابقتی قیمتیں",

    // Featured Section
    featuredTrucks: "نمایاں ٹرکس",
    viewAll: "سب دیکھیں",
    loading: "لوڈ ہو رہا ہے…",
    loadFailed: "اشتہارات لوڈ نہیں ہو سکے۔ کیا API چل رہا ہے؟",

    // CTA
    readyToSell: "اپنا ٹرک بیچنے کے لیے تیار ہیں؟",
    readyToSellDesc: "اپنا ٹرک مفت میں درج کریں اور ہزاروں ممکنہ خریداروں تک پہنچیں۔ انفرادی بیچنے والے اور کمپنیاں خوش آمدید۔",
    getStarted: "شروع کریں",

    // Categories
    allTrucks: "تمام ٹرکس",
    traditional: "روایتی",
    lightCommercial: "ہلکی کمرشل",
    constructionEquipment: "تعمیراتی سامان",
    catTractorhead: "ٹریکٹر ہیڈ",
    catTruckRigid: "ٹرک",
    catLightCommercialVehicle: "ہلکی کمرشل گاڑی",
    catConstructionEquipment: "تعمیراتی سامان",
    catSemiTrailer: "سیمی ٹریلر",

    // Truck Types
    commercial: "کمرشل",
    pickup: "پک اپ",
    van: "وین",
    dump: "ڈمپ ٹرک",
    flatbed: "فلیٹ بیڈ",
    semi: "سیمی ٹرک",

    // Inventory Page
    browseInventoryTitle: "انوینٹری براؤز کریں",
    searchPlaceholder: "میک، ماڈل، یا مقام سے تلاش کریں...",
    sortBy: "ترتیب دیں بلحاظ",
    filters: "فلٹرز",
    clear: "صاف کریں",
    clearAllFilters: "تمام فلٹرز صاف کریں",
    showingResults: "دکھایا جا رہا ہے",
    of: "از",
    trucks: "ٹرکس",
    noTrucksFound: "آپ کے معیار سے مماثل کوئی ٹرک نہیں ملا",

    // Sort Options
    newestFirst: "پہلے تازہ ترین",
    priceLowToHigh: "قیمت: کم سے زیادہ",
    priceHighToLow: "قیمت: زیادہ سے کم",
    yearNewest: "سال: تازہ ترین",
    yearOldest: "سال: قدیم ترین",
    mileageLowToHigh: "مائلیج: کم سے زیادہ",
    mileageHighToLow: "مائلیج: زیادہ سے کم",

    // Filters
    truckType: "ٹرک کی قسم",
    condition: "حالت",
    priceRange: "قیمت کی حد",
    yearRange: "سال",
    mileageRange: "مائلیج",
    transmission: "ٹرانسمیشن",
    fuelType: "ایندھن کی قسم",
    sellerType: "بیچنے والے کی قسم",

    // Condition
    excellent: "بہترین",
    good: "اچھا",
    fair: "مناسب",
    notWorking: "خراب / کام نہیں کرتا",

    // Transmission
    automatic: "آٹومیٹک",
    manual: "مینوئل",

    // Fuel Type
    diesel: "ڈیزل",
    gasoline: "پیٹرول",
    electric: "الیکٹرک",
    hybrid: "ہائبرڈ",

    // Seller Type
    individual: "فرد",
    company: "کمپنی",

    // Truck Card
    miles: "میل",
    listingRef: "حوالہ نمبر",

    // Truck Detail
    back: "واپس",
    mileage: "مائلیج",
    year: "سال",
    description: "تفصیل",
    features: "خصوصیات",
    sellerInformation: "بیچنے والے کی معلومات",
    callSeller: "بیچنے والے کو کال کریں",
    sendMessage: "پیغام بھیجیں",
    additionalInformation: "اضافی معلومات",
    listed: "درج شدہ",
    type: "قسم",
    interestedTitle: "اس ٹرک میں دلچسپی ہے؟",
    interestedDesc: "معائنہ طے کرنے یا مزید معلومات حاصل کرنے کے لیے براہ راست بیچنے والے سے رابطہ کریں۔",
    requestInformation: "معلومات کی درخواست کریں",
    truckNotFound: "ٹرک نہیں ملا",
    backToInventory: "انوینٹری پر واپس جائیں",

    // Add Truck Page
    listTruckTitle: "فروخت کے لیے اپنا ٹرک درج کریں",
    listTruckDesc: "اپنا ٹرک ہماری مارکیٹ پلیس میں شامل کرنے کے لیے نیچے دیا گیا فارم پُر کریں",
    sellFlowTitle: "اپنے ٹرکس بیچیں",
    sellFlowQuestion: "آپ کیا بیچنا چاہتے ہیں؟",
    sellContinue: "جاری رکھیں",
    changeCategory: "زمرہ تبدیل کریں",
    typeLockedHint:
      "گاڑی کی قسم آپ کے زمرے سے متعین ہے۔ اگر فہرست میں نہ ہو تو آپ پھر بھی کوئی بھی میک یا ماڈل ٹائپ کر سکتے ہیں۔",
    sellCatTractorUnit: "ٹریکٹر یونٹ",
    sellCatRigidTruck: "ٹرک",
    sellCatSemiTrailers: "سیمی ٹریلرز",
    sellCatVan: "وین",
    sellCatAgriculture: "زرعی",
    sellCatMachine: "مشین",
    sellCatVarious: "متفرق",

    aiCategoryStepHint:
      "گاڑی کی تصویر اپ لوڈ کریں اور ہم بہترین زمرہ تجویز کریں گے (سرور کی ترتیب درکار ہے)۔",
    aiCategorySuggestFromPhoto: "تصویر سے زمرہ تجویز کریں",
    aiCategorySelectedToast: "تجویز کردہ زمرہ: {label}",
    aiCategoryUnavailable:
      "AI زمرہ شناخت سرور پر ترتیب نہیں دی گئی (OPENAI_API_KEY سیٹ کریں)۔",
    aiCategoryFailed: "تصویر کا تجزیہ نہیں ہو سکا۔ دوبارہ کوشش کریں یا زمرہ خود منتخب کریں۔",
    aiCategoryAnalyzing: "زمرے کے لیے پہلی تصویر کا تجزیہ ہو رہا ہے…",
    aiCategorySuggestionTitle: "زمرے کی تجویز",
    aiCategorySuggestionBody:
      "یہ تصویر {label} جیسی لگتی ہے (تقریباً {percent}% اعتماد)۔ اسے لاگو کریں یا اپنا موجودہ زمرہ برقرار رکھیں۔",
    aiCategoryApplySuggestion: "تجویز لاگو کریں",
    aiCategoryKeepChoice: "موجودہ رکھیں",
    basicInformation: "بنیادی معلومات",
    make: "میک",
    model: "ماڈل",
    selectMakePlaceholder: "میک منتخب کریں…",
    selectModelPlaceholder: "ماڈل منتخب کریں…",
    selectMakeFirstModel: "پہلے میک منتخب کریں",
    searchMakePlaceholder: "میک تلاش کریں…",
    searchModelPlaceholder: "ماڈل تلاش کریں…",
    comboboxEmptyMakes: "انوینٹری میں کوئی میک نہیں — شامل کرنے کے لیے ٹائپ کریں",
    comboboxEmptyModels: "اس میک کے لیے کوئی ماڈل نہیں — شامل کرنے کے لیے ٹائپ کریں",
    selectYearPlaceholder: "سال منتخب کریں…",
    comboboxEmptyYears: "کوئی مماثل سال نہیں",
    trailerMakeModelHint:
      "سیمی ٹریلرز اور ٹریلرز اکثر برانڈ کی فہرست میں موجود نہیں ہوتے۔ کم از کم برانڈ یا ماڈل/تفصیلات (مثلاً سائز یا سیریز) درج کریں۔ آپ ایک خانہ پُر کر کے دوسرا خالی چھوڑ سکتے ہیں۔",
    makeOrModelRequired: "کم از کم ایک برانڈ یا ماڈل درج کریں۔",
    selectModelTrailerPlaceholder: "مثلاً سیریز، لمبائی، یا تفصیلات",
    useCustomValue: "\"{value}\" استعمال کریں",
    price: "قیمت (سعودی ریال)",
    location: "مقام",
    listingState: "ریاست",
    listingCity: "شہر",
    selectStatePlaceholder: "ریاست منتخب کریں…",
    selectCityPlaceholder: "شہر منتخب کریں…",
    selectStateFirstCity: "پہلے ریاست منتخب کریں",
    comboboxEmptyRegions: "کوئی مماثل ریاست نہیں",
    comboboxEmptyCities: "کوئی مماثل شہر نہیں",
    truckDetails: "ٹرک کی تفصیلات",
    companyName: "کمپنی کا نام",
    yourName: "آپ کا نام",
    descriptionAndFeatures: "تفصیل اور خصوصیات",
    descriptionPlaceholder: "اختیاری — اپنے ٹرک کے بارے میں تفصیلات شامل کریں…",
    featuresPlaceholder: "مثلاً ایئر کنڈیشننگ، بیک اپ کیمرہ، بلوٹوتھ",
    featuresSeparate: "خصوصیات کو کوما سے الگ کریں",
    imageUploadLabel: "اشتہار کی تصاویر",
    imageUploadHelp:
      "زیادہ سے زیادہ 10 تصاویر — JPEG، PNG، WebP، یا GIF، ہر ایک زیادہ سے زیادہ 5 MB۔ اگر آپ تصاویر نہ دیں تو ڈیفالٹ تصویر استعمال ہوگی۔",
    imageUploading: "اپ لوڈ ہو رہا ہے…",
    imageUploadFailed: "تصویر اپ لوڈ نہیں ہو سکی۔ دوبارہ کوشش کریں۔",
    tooManyImages: "آپ زیادہ سے زیادہ 10 تصاویر شامل کر سکتے ہیں۔",
    videoUploadLabel: "اشتہار کی ویڈیو (اختیاری)",
    videoUploadHelp: "MP4، WebM، یا MOV — زیادہ سے زیادہ 80 MB۔",
    videoUploading: "ویڈیو اپ لوڈ ہو رہی ہے…",
    videoUploadFailed: "ویڈیو اپ لوڈ نہیں ہو سکی۔ دوبارہ کوشش کریں۔",
    removeVideo: "ویڈیو ہٹائیں",
    listTruck: "ٹرک درج کریں",
    cancel: "منسوخ کریں",

    // Form Validation
    optional: "اختیاری",
    required: "درکار ہے",
    yearMin: "سال 1970 یا اس کے بعد کا ہونا چاہیے",
    yearMax: "سال مستقبل میں نہیں ہو سکتا",
    mileageMin: "مائلیج مثبت ہونی چاہیے",
    priceMin: "قیمت مثبت ہونی چاہیے",
    descriptionMin: "تفصیل کم از کم 50 حروف کی ہونی چاہیے",

    // Toast Messages
    truckAddedSuccess: "ٹرک کا اشتہار کامیابی سے شامل ہو گیا!",
    saveFailed: "اشتہار محفوظ نہیں ہو سکا۔ دوبارہ کوشش کریں۔",

    // 404 Page
    pageNotFound: "صفحہ نہیں ملا",
    pageNotFoundDesc: "جو صفحہ آپ تلاش کر رہے ہیں وہ موجود نہیں ہے یا منتقل کر دیا گیا ہے۔",
    goBackHome: "ہوم پیج پر واپس جائیں",

    // Site footer
    footerColBuy: "خریدیں",
    footerViewStock: "اسٹاک دیکھیں",
    footerHowToBuy: "گاڑی کیسے خریدیں",
    footerColSell: "بیچیں",
    footerStartSelling: "بیچنا شروع کریں",
    footerColHelp: "مدد",
    footerContact: "رابطہ کریں",
    footerCareers: "ملازمتیں",
    footerColLearn: "جانیں",
    footerAbout: "Trucks کے بارے میں",
    footerNews: "خبریں",
    footerEthics: "اخلاقیات",
    footerSubscribeNewsletter: "ہمارے نیوز لیٹر کو سبسکرائب کریں",
    footerPrivacy: "پرائیویسی پالیسی",
    footerCookie: "کوکی پالیسی",
    footerSitemap: "سائٹ میپ",
    footerCopyright: "© کاپی رائٹ 2026 Trucks",
    footerAnyQuestions: "کوئی سوالات ہیں؟",
    footerDismissQuestionWidget: "چھپائیں",
    footerSocialAria: "Trucks {network} پر",
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("ar");

  useEffect(() => {
    document.documentElement.lang = language;
    document.documentElement.dir = RTL_LANGUAGES.includes(language) ? "rtl" : "ltr";
  }, [language]);

  const toggleLanguage = () => {
    setLanguage((prev) => {
      const idx = LANGUAGE_ORDER.indexOf(prev);
      return LANGUAGE_ORDER[(idx + 1) % LANGUAGE_ORDER.length];
    });
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.en] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
}
