import React, { createContext, useContext, useEffect, useState, ReactNode } from "react";

type Language = "en" | "ar";

interface LanguageContextType {
  language: Language;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Header
    siteName: "MarketSmart",
    home: "Home",
    inventory: "Inventory",
    sellYourTruck: "Sell Your Truck",
    loginTitle: "Log in",
    loginSubtitle: "Sign in to list your truck on MarketSmart.",
    loginAction: "Log in",
    loginSuccess: "Welcome back!",
    loginFailed: "Could not log in. Check your email and password.",
    signupTitle: "Create an account",
    signupSubtitle: "Sign up to post your truck listing.",
    signupAction: "Sign up",
    signupSuccess: "Account created!",
    signupFailed: "Could not sign up. Try a different email.",
    email: "Email",
    password: "Password",
    confirmPassword: "Confirm password",
    firstName: "First name",
    lastName: "Last name",
    mobileNumber: "Mobile number",
    accountType: "Account type",
    accountTypeQuestion: "How will you use MarketSmart?",
    accountTypeIndividual: "Individual",
    accountTypeCompany: "Company / Establishment",
    accountTypeContinue: "Continue",
    changeAccountType: "Change account type",
    companyNameRequired: "Company name is required.",
    crNumberLabel: "Commercial registration number (CR)",
    crNumberPlaceholder: "10-digit CR number",
    crNumberInvalid: "Enter a valid 10-digit commercial registration number.",
    hasVatLabel: "This establishment has a VAT number",
    vatNumberLabel: "VAT number",
    vatNumberPlaceholder: "15 digits, starts and ends with 3",
    vatNumberInvalid: "Enter a valid 15-digit VAT number (starts and ends with 3).",
    passwordMismatch: "Passwords do not match.",
    noAccount: "Don't have an account?",
    haveAccount: "Already have an account?",
    signUp: "Sign up",
    logIn: "Log in",
    logout: "Log out",
    signedInAs: "Signed in as",
    profileAccount: "Account",
    profileTitle: "Your account",
    profileSubtitle: "Buyer inquiries about your listings.",
    accountDetails: "Account details",
    fullNameLabel: "Name",
    yes: "Yes",
    no: "No",
    companyProfileTitle: "Company profile",
    companyProfileDesc: "Shown to buyers on your listings and used for how they reach you.",
    registeredCompanyInfo: "Registered company info",
    companyLogoLabel: "Company logo",
    uploadLogo: "Upload logo",
    changeLogo: "Change logo",
    removeLogo: "Remove",
    logoUploadFailed: "Could not upload logo. Try again.",
    additionalPhonesLabel: "Additional contact numbers",
    additionalPhonesHelp: "Add extra numbers buyers can use to reach your company (e.g. a sales line).",
    addPhoneNumber: "Add number",
    removeNumber: "Remove number",
    representativeNameLabel: "Responsible representative — name",
    representativePhoneLabel: "Responsible representative — phone",
    saveCompanyProfile: "Save company profile",
    companyProfileUpdated: "Company profile updated.",
    companyProfileUpdateFailed: "Could not update company profile.",
    companyStatusPending: "Pending review",
    companyStatusApproved: "Approved",
    companyStatusRejected: "Rejected",
    companyStatusPendingHelp:
      "Your company account is awaiting admin review. You'll be able to list vehicles once approved.",
    companyStatusRejectedHelp:
      "Your company account was not approved. Check your details and commercial registration document, then contact support if you believe this is a mistake.",
    crDocumentLabel: "Commercial registration document",
    crDocumentHelp: "Upload a copy of your commercial registration certificate (PDF, JPG, PNG, or WebP).",
    crDocumentRequired: "Please attach your commercial registration document.",
    uploadCrDocument: "Upload document",
    replaceCrDocument: "Replace document",
    viewCrDocument: "View document",
    noCrDocument: "No document uploaded yet.",
    crDocumentUploadFailed: "Could not upload the document. Try again.",
    crDocumentUploadFailedAfterSignup:
      "Account created, but the document upload failed. Add it from your account page.",
    termsRequired: "You must agree to the Terms and Conditions to continue.",
    agreeToTermsPrefix: "I agree to the",
    termsAndConditionsLink: "Terms and Conditions",
    termsContent:
      "1. Acceptance of terms\nBy creating an account you agree to use MarketSmart responsibly and in accordance with these terms.\n\n2. Account responsibility\nYou are responsible for the accuracy of the information you provide, including company and contact details, and for keeping your login credentials secure.\n\n3. Listings\nListings must be accurate and describe vehicles you own or are authorized to sell. MarketSmart may remove listings that are misleading, fraudulent, or violate applicable law.\n\n4. Marketplace role\nMarketSmart provides a platform connecting buyers and sellers. MarketSmart is not a party to any sale between users and does not guarantee the condition, legality, or value of any listed vehicle.\n\n5. Company verification\nCompany accounts are subject to review, including verification of the commercial registration document, before they may publish listings.\n\n6. Prohibited conduct\nYou may not use the platform for unlawful purposes, to post fraudulent listings, or to harass other users.\n\n7. Limitation of liability\nMarketSmart is not liable for disputes, losses, or damages arising from transactions between users.\n\n8. Changes\nThese terms may be updated from time to time; continued use of the platform constitutes acceptance of the updated terms.",
    adminNavLink: "Admin",
    adminCompaniesTitle: "Company accounts",
    adminCompaniesSubtitle: "Review company signups and approve or reject their access to list vehicles.",
    adminAllCompanies: "All",
    adminNoCompanies: "No company accounts in this view.",
    adminLoadFailed: "Could not load company accounts.",
    adminApprove: "Approve",
    adminReject: "Reject",
    adminStatusUpdated: "Status updated.",
    adminStatusUpdateFailed: "Could not update status.",
    securitySettings: "Security",
    changePasswordTitle: "Change password",
    currentPasswordLabel: "Current password",
    newPasswordLabel: "New password",
    confirmNewPasswordLabel: "Confirm new password",
    savePassword: "Update password",
    passwordUpdated: "Password updated.",
    passwordMismatchProfile: "New passwords do not match.",
    passwordMinEight: "Password must be at least 8 characters.",
    changePhoneTitle: "Mobile number",
    changePhoneIntro:
      "To change your number, we send a verification code to your current number.",
    phoneChangeNoNumber: "No number on file. Enter your password and the number you want to use.",
    accountPasswordLabel: "Account password",
    sendCode: "Send verification code",
    codeSentToast: "A verification code has been sent to your number.",
    devCodeHint: "Development: your code is",
    verificationCodeLabel: "Verification code",
    newPhoneLabel: "New mobile number",
    confirmPhoneChange: "Save new number",
    phoneUpdated: "Mobile number updated.",
    phoneStep2Hint: "Enter the code you received, then your new number.",
    manageSecuritySettings: "Security",
    hideSecuritySettings: "Hide",
    myAdverts: "My adverts",
    myAdvertsTitle: "My adverts",
    myAdvertsSubtitle: "Listings you have published — open or edit any of them.",
    myAdvertsEmpty: "You have not listed any trucks yet.",
    editListing: "Edit listing",
    editListingTitle: "Edit listing",
    editListingDesc: "Update your listing details and photos. Save when you are done.",
    listingUpdatedSuccess: "Listing updated.",
    editNotOwner: "You can only edit your own listings.",
    saveListing: "Save changes",
    btnReserved: "Reserved",
    btnSold: "Sold",
    btnBackToActive: "Back to active",
    btnBackToActiveHelp:
      "Cancel reserved/sold status if the deal did not go through — listing is visible in search again.",
    statusReserved: "Reserved",
    statusSold: "Sold",
    statusActive: "Active",
    listingStatusUpdated: "Listing status updated.",
    listingSoldBanner: "This listing is marked as sold.",
    listingReservedBanner: "This listing is reserved.",
    listingSoldNoContact: "This truck is sold — messaging is closed.",
    listingInactiveNoContact:
      "Messaging is not available while this listing is reserved or otherwise unavailable.",
    buyerMessagesTitle: "Buyer messages",
    noBuyerMessages:
      "No messages yet. When a buyer contacts you about a listing, it will appear here.",
    fromBuyer: "From",
    yourMessagesToSellers: "Your messages to sellers",
    yourMessagesToSellersHelp: "Questions you sent about listings — seller replies appear below.",
    noSentMessages: "You have not messaged any sellers yet.",
    sellerReplyLabel: "Seller reply",
    yourReplyLabel: "Your reply",
    replyPlaceholder: "Write your reply to the buyer…",
    sendReply: "Send reply",
    replyEmpty: "Reply cannot be empty.",
    replyFailed: "Could not send reply.",
    replySentSuccess: "Reply sent.",
    yourMessageToSeller: "Your message",
    waitingForSellerReply: "The seller has not replied yet.",
    chatNotificationsTitle: "Messages",
    noChatThreads: "No conversations yet.",
    openAccountMessages: "Account & all chats",
    openChat: "Open chat",
    unreadMessages: "unread",
    chatLoadFailed: "Could not load this chat.",
    chatInvalidThread: "Invalid conversation.",
    chatYouAreSeller: "You are the seller in this chat.",
    chatYouAreBuyer: "You contacted the seller about this listing.",
    viewListing: "View listing",
    chatReplyPlaceholder: "Type a message… (Enter to send, Shift+Enter for new line)",
    sellerPhoneLabel: "Phone number",
    sellerPhoneHelp: "Buyers can use this number to call you about this listing.",
    loginToSendMessage: "Log in to send a message to the seller.",
    sendMessageAction: "Send message",
    messagePlaceholder: "Write your message…",
    messageSentSuccess: "Message sent.",
    messageSendFailed: "Could not send message.",
    ownListingNoMessage: "This is your listing.",
    listingCannotReceiveMessages: "This listing cannot receive messages.",

    // Home Page
    heroTitle: "Find Your Perfect Commercial Truck",
    heroSubtitle: "Browse thousands of quality used and commercial trucks from trusted sellers nationwide",
    browseInventory: "Browse Inventory",
    listYourTruck: "List Your Truck",
    
    // Features
    advancedSearch: "Advanced Search",
    advancedSearchDesc: "Filter by make, model, year, price, mileage and more to find exactly what you need",
    trustedSellers: "Trusted Sellers",
    trustedSellersDesc: "Buy from verified individual sellers and reputable commercial dealerships",
    bestPrices: "Best Prices",
    bestPricesDesc: "Competitive pricing on quality trucks with transparent pricing and detailed specs",
    
    // Featured Section
    featuredTrucks: "Featured Trucks",
    viewAll: "View All",
    loading: "Loading…",
    loadFailed: "Could not load listings. Is the API running?",
    
    // CTA
    readyToSell: "Ready to Sell Your Truck?",
    readyToSellDesc: "List your truck for free and reach thousands of potential buyers. Individual sellers and companies welcome.",
    getStarted: "Get Started",
    
    // Categories
    allTrucks: "All Trucks",
    traditional: "Traditional",
    lightCommercial: "Light Commercial",
    constructionEquipment: "Construction Equipment",
    catTractorhead: "Tractorhead",
    catTruckRigid: "Truck",
    catLightCommercialVehicle: "Light commercial vehicle",
    catConstructionEquipment: "Construction equipment",
    catSemiTrailer: "Semi-trailer",

    // Truck Types
    commercial: "Commercial",
    pickup: "Pickup",
    van: "Van",
    dump: "Dump Truck",
    flatbed: "Flatbed",
    semi: "Semi Truck",
    
    // Inventory Page
    browseInventoryTitle: "Browse Inventory",
    searchPlaceholder: "Search by make, model, or location...",
    sortBy: "Sort by",
    filters: "Filters",
    clear: "Clear",
    clearAllFilters: "Clear All Filters",
    showingResults: "Showing",
    of: "of",
    trucks: "trucks",
    noTrucksFound: "No trucks found matching your criteria",
    
    // Sort Options
    newestFirst: "Newest First",
    priceLowToHigh: "Price: Low to High",
    priceHighToLow: "Price: High to Low",
    yearNewest: "Year: Newest",
    yearOldest: "Year: Oldest",
    mileageLowToHigh: "Mileage: Low to High",
    mileageHighToLow: "Mileage: High to Low",
    
    // Filters
    truckType: "Truck Type",
    condition: "Condition",
    priceRange: "Price Range",
    yearRange: "Year",
    mileageRange: "Mileage",
    transmission: "Transmission",
    fuelType: "Fuel Type",
    sellerType: "Seller Type",
    
    // Condition
    excellent: "Excellent",
    good: "Good",
    fair: "Fair",
    notWorking: "Not Working",
    
    // Transmission
    automatic: "Automatic",
    manual: "Manual",
    
    // Fuel Type
    diesel: "Diesel",
    gasoline: "Gasoline",
    electric: "Electric",
    hybrid: "Hybrid",
    
    // Seller Type
    individual: "Individual",
    company: "Company",
    
    // Truck Card
    miles: "miles",
    listingRef: "Ref.",
    
    // Truck Detail
    back: "Back",
    mileage: "Mileage",
    year: "Year",
    description: "Description",
    features: "Features",
    sellerInformation: "Seller Information",
    callSeller: "Call Seller",
    sendMessage: "Send Message",
    additionalInformation: "Additional Information",
    listed: "Listed",
    type: "Type",
    interestedTitle: "Interested in this truck?",
    interestedDesc: "Contact the seller directly to schedule a viewing or get more information.",
    requestInformation: "Request Information",
    truckNotFound: "Truck not found",
    backToInventory: "Back to Inventory",
    
    // Add Truck Page
    listTruckTitle: "List Your Truck for Sale",
    listTruckDesc: "Fill out the form below to add your truck to our marketplace",
    sellFlowTitle: "Sell your trucks",
    sellFlowQuestion: "What do you want to sell?",
    sellContinue: "Continue",
    changeCategory: "Change category",
    typeLockedHint:
      "Vehicle type is set from your category. You can still type any make or model if it is not in the list.",
    sellCatTractorUnit: "Tractor unit",
    sellCatRigidTruck: "Truck",
    sellCatSemiTrailers: "Semi-trailers",
    sellCatVan: "Van",
    sellCatAgriculture: "Agriculture",
    sellCatMachine: "Machine",
    sellCatVarious: "Various",

    aiCategoryStepHint:
      "Upload a photo of the vehicle and we will suggest the best category (requires server setup).",
    aiCategorySuggestFromPhoto: "Suggest category from photo",
    aiCategorySelectedToast: "Suggested category: {label}",
    aiCategoryUnavailable:
      "AI category detection is not configured on the server (set OPENAI_API_KEY).",
    aiCategoryFailed: "Could not analyze the photo. Try again or pick a category manually.",
    aiCategoryAnalyzing: "Analyzing first photo for category…",
    aiCategorySuggestionTitle: "Category suggestion",
    aiCategorySuggestionBody:
      "This photo looks like {label} (about {percent}% confidence). Apply it or keep your current category.",
    aiCategoryApplySuggestion: "Apply suggestion",
    aiCategoryKeepChoice: "Keep current",
    basicInformation: "Basic Information",
    make: "Make",
    model: "Model",
    selectMakePlaceholder: "Select make…",
    selectModelPlaceholder: "Select model…",
    selectMakeFirstModel: "Select a make first",
    searchMakePlaceholder: "Search makes…",
    searchModelPlaceholder: "Search models…",
    comboboxEmptyMakes: "No makes in inventory — type to add one",
    comboboxEmptyModels: "No models for this make — type to add one",
    selectYearPlaceholder: "Select year…",
    comboboxEmptyYears: "No matching years",
    trailerMakeModelHint:
      "Semi-trailers and trailers are often missing from the brand list. Enter at least a brand or a model/spec (e.g. size, series). You can fill one field and leave the other empty.",
    makeOrModelRequired: "Enter at least a brand or a model.",
    selectModelTrailerPlaceholder: "e.g. series, length, or specs",
    useCustomValue: "Use \"{value}\"",
    price: "Price (Saudi Riyals)",
    location: "Location",
    listingState: "State",
    listingCity: "City",
    selectStatePlaceholder: "Select state…",
    selectCityPlaceholder: "Select city…",
    selectStateFirstCity: "Select state first",
    comboboxEmptyRegions: "No matching states",
    comboboxEmptyCities: "No matching cities",
    truckDetails: "Truck Details",
    companyName: "Company Name",
    yourName: "Your Name",
    descriptionAndFeatures: "Description & Features",
    descriptionPlaceholder: "Optional — add details about your truck…",
    featuresPlaceholder: "e.g., Air Conditioning, Backup Camera, Bluetooth",
    featuresSeparate: "Separate features with commas",
    imageUploadLabel: "Listing photos",
    imageUploadHelp:
      "Up to 10 photos — JPEG, PNG, WebP, or GIF, max 5 MB each. A default image is used if you skip photos.",
    imageUploading: "Uploading…",
    imageUploadFailed: "Could not upload image. Try again.",
    tooManyImages: "You can add at most 10 photos.",
    videoUploadLabel: "Listing video (optional)",
    videoUploadHelp: "MP4, WebM, or MOV — max 80 MB.",
    videoUploading: "Uploading video…",
    videoUploadFailed: "Could not upload video. Try again.",
    removeVideo: "Remove video",
    listTruck: "List Truck",
    cancel: "Cancel",
    
    // Form Validation
    optional: "optional",
    required: "is required",
    yearMin: "Year must be 1970 or later",
    yearMax: "Year cannot be in the future",
    mileageMin: "Mileage must be positive",
    priceMin: "Price must be positive",
    descriptionMin: "Description must be at least 50 characters",
    
    // Toast Messages
    truckAddedSuccess: "Truck listing added successfully!",
    saveFailed: "Could not save listing. Try again.",
    
    // 404 Page
    pageNotFound: "Page Not Found",
    pageNotFoundDesc: "The page you're looking for doesn't exist or has been moved.",
    goBackHome: "Go Back Home",

    // Site footer
    footerColBuy: "Buy",
    footerViewStock: "View stock",
    footerHowToBuy: "How to buy a vehicle",
    footerColSell: "Sell",
    footerStartSelling: "Start selling",
    footerColHelp: "Help",
    footerContact: "Contact",
    footerCareers: "Careers",
    footerColLearn: "Learn",
    footerAbout: "About MarketSmart",
    footerNews: "News",
    footerEthics: "Ethics",
    footerSubscribeNewsletter: "Subscribe to our newsletter",
    footerPrivacy: "Privacy policy",
    footerCookie: "Cookie policy",
    footerSitemap: "Sitemap",
    footerCopyright: "© Copyright 2026 MarketSmart",
    footerAnyQuestions: "Any questions?",
    footerDismissQuestionWidget: "Hide",
    footerSocialAria: "MarketSmart on {network}",
  },
  ar: {
    // Header
    siteName: "MarketSmart",
    home: "الرئيسية",
    inventory: "المخزون",
    sellYourTruck: "بيع شاحنتك",
    loginTitle: "تسجيل الدخول",
    loginSubtitle: "سجّل الدخول لإدراج شاحنتك على MarketSmart.",
    loginAction: "تسجيل الدخول",
    loginSuccess: "مرحباً بعودتك!",
    loginFailed: "تعذر تسجيل الدخول. تحقق من البريد وكلمة المرور.",
    signupTitle: "إنشاء حساب",
    signupSubtitle: "سجّل حساباً لنشر إعلان شاحنتك.",
    signupAction: "إنشاء حساب",
    signupSuccess: "تم إنشاء الحساب!",
    signupFailed: "تعذر التسجيل. جرّب بريداً آخر.",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    confirmPassword: "تأكيد كلمة المرور",
    firstName: "الاسم الأول",
    lastName: "اسم العائلة",
    mobileNumber: "رقم الجوال",
    accountType: "نوع الحساب",
    accountTypeQuestion: "كيف تريد استخدام MarketSmart؟",
    accountTypeIndividual: "فرد",
    accountTypeCompany: "منشأة",
    accountTypeContinue: "متابعة",
    changeAccountType: "تغيير نوع الحساب",
    companyNameRequired: "اسم المنشأة مطلوب.",
    crNumberLabel: "رقم السجل التجاري",
    crNumberPlaceholder: "رقم السجل التجاري (10 أرقام)",
    crNumberInvalid: "أدخل رقم سجل تجاري صحيح مكوّن من 10 أرقام.",
    hasVatLabel: "لدى المنشأة رقم ضريبي (VAT)",
    vatNumberLabel: "الرقم الضريبي",
    vatNumberPlaceholder: "15 رقماً، يبدأ وينتهي بالرقم 3",
    vatNumberInvalid: "أدخل رقماً ضريبياً صحيحاً مكوّناً من 15 رقماً (يبدأ وينتهي بالرقم 3).",
    passwordMismatch: "كلمتا المرور غير متطابقتين.",
    noAccount: "ليس لديك حساب؟",
    haveAccount: "لديك حساب بالفعل؟",
    signUp: "إنشاء حساب",
    logIn: "تسجيل الدخول",
    logout: "تسجيل الخروج",
    signedInAs: "مسجّل دخولك كـ",
    profileAccount: "الحساب",
    profileTitle: "حسابك",
    profileSubtitle: "استفسارات المشترين عن إعلاناتك.",
    accountDetails: "تفاصيل الحساب",
    fullNameLabel: "الاسم",
    yes: "نعم",
    no: "لا",
    companyProfileTitle: "بيانات الشركة",
    companyProfileDesc: "تظهر للمشترين في إعلاناتك وتُستخدم للتواصل معك.",
    registeredCompanyInfo: "بيانات التسجيل",
    companyLogoLabel: "شعار الشركة",
    uploadLogo: "رفع الشعار",
    changeLogo: "تغيير الشعار",
    removeLogo: "إزالة",
    logoUploadFailed: "تعذر رفع الشعار. حاول مرة أخرى.",
    additionalPhonesLabel: "أرقام تواصل إضافية",
    additionalPhonesHelp: "أضف أرقاماً إضافية يمكن للمشترين استخدامها للتواصل مع شركتك (مثل خط المبيعات).",
    addPhoneNumber: "إضافة رقم",
    removeNumber: "إزالة الرقم",
    representativeNameLabel: "المندوب المسؤول — الاسم",
    representativePhoneLabel: "المندوب المسؤول — الجوال",
    saveCompanyProfile: "حفظ بيانات الشركة",
    companyProfileUpdated: "تم تحديث بيانات الشركة.",
    companyProfileUpdateFailed: "تعذر تحديث بيانات الشركة.",
    companyStatusPending: "قيد المراجعة",
    companyStatusApproved: "مفعّل",
    companyStatusRejected: "مرفوض",
    companyStatusPendingHelp:
      "حساب منشأتك بانتظار مراجعة الإدارة. ستتمكن من إدراج المركبات بعد الموافقة عليه.",
    companyStatusRejectedHelp:
      "لم تتم الموافقة على حساب منشأتك. تحقق من بياناتك ووثيقة السجل التجاري، وتواصل مع الدعم إذا كنت تعتقد أن هذا خطأ.",
    crDocumentLabel: "وثيقة السجل التجاري",
    crDocumentHelp: "ارفع نسخة من شهادة السجل التجاري (PDF أو JPG أو PNG أو WebP).",
    crDocumentRequired: "الرجاء إرفاق وثيقة السجل التجاري.",
    uploadCrDocument: "رفع الوثيقة",
    replaceCrDocument: "استبدال الوثيقة",
    viewCrDocument: "عرض الوثيقة",
    noCrDocument: "لم يتم رفع أي وثيقة بعد.",
    crDocumentUploadFailed: "تعذر رفع الوثيقة. حاول مرة أخرى.",
    crDocumentUploadFailedAfterSignup:
      "تم إنشاء الحساب، لكن تعذر رفع الوثيقة. أضفها من صفحة حسابك.",
    termsRequired: "يجب الموافقة على الشروط والأحكام للمتابعة.",
    agreeToTermsPrefix: "أوافق على",
    termsAndConditionsLink: "الشروط والأحكام",
    termsContent:
      "1. قبول الشروط\nبإنشائك حساباً فإنك توافق على استخدام MarketSmart بمسؤولية ووفقاً لهذه الشروط.\n\n2. مسؤولية الحساب\nأنت مسؤول عن دقة المعلومات التي تقدمها، بما في ذلك بيانات المنشأة وبيانات التواصل، وعن الحفاظ على سرية بيانات الدخول الخاصة بك.\n\n3. الإعلانات\nيجب أن تكون الإعلانات دقيقة وتصف مركبات تملكها أو مخوّل ببيعها. يحق لـ MarketSmart إزالة أي إعلان مضلل أو احتيالي أو يخالف الأنظمة المعمول بها.\n\n4. دور المنصة\nتوفر MarketSmart منصة تربط البائعين بالمشترين، وهي ليست طرفاً في أي عملية بيع بين المستخدمين ولا تضمن حالة أو قانونية أو قيمة أي مركبة معروضة.\n\n5. التحقق من المنشآت\nتخضع حسابات المنشآت للمراجعة، بما في ذلك التحقق من وثيقة السجل التجاري، قبل السماح لها بنشر الإعلانات.\n\n6. السلوك المحظور\nلا يجوز استخدام المنصة لأغراض مخالفة للنظام، أو نشر إعلانات احتيالية، أو مضايقة المستخدمين الآخرين.\n\n7. حدود المسؤولية\nلا تتحمل MarketSmart مسؤولية أي نزاعات أو خسائر أو أضرار ناتجة عن معاملات بين المستخدمين.\n\n8. التعديلات\nقد يتم تحديث هذه الشروط من وقت لآخر؛ ويُعد استمرارك في استخدام المنصة موافقة على الشروط المحدثة.",
    adminNavLink: "الإدارة",
    adminCompaniesTitle: "حسابات المنشآت",
    adminCompaniesSubtitle: "راجع طلبات تسجيل المنشآت ووافق أو ارفض السماح لها بإدراج المركبات.",
    adminAllCompanies: "الكل",
    adminNoCompanies: "لا توجد حسابات منشآت في هذا العرض.",
    adminLoadFailed: "تعذر تحميل حسابات المنشآت.",
    adminApprove: "موافقة",
    adminReject: "رفض",
    adminStatusUpdated: "تم تحديث الحالة.",
    adminStatusUpdateFailed: "تعذر تحديث الحالة.",
    securitySettings: "الأمان",
    changePasswordTitle: "تغيير كلمة المرور",
    currentPasswordLabel: "كلمة المرور الحالية",
    newPasswordLabel: "كلمة المرور الجديدة",
    confirmNewPasswordLabel: "تأكيد كلمة المرور الجديدة",
    savePassword: "تحديث كلمة المرور",
    passwordUpdated: "تم تحديث كلمة المرور.",
    passwordMismatchProfile: "كلمتا المرور الجديدتان غير متطابقتين.",
    passwordMinEight: "يجب أن تكون كلمة المرور 8 أحرف على الأقل.",
    changePhoneTitle: "رقم الجوال",
    changePhoneIntro: "لتغيير الرقم نرسل رمز تحقق إلى رقمك الحالي.",
    phoneChangeNoNumber: "لا يوجد رقم محفوظ. أدخل كلمة مرورك والرقم الذي تريد استخدامه.",
    accountPasswordLabel: "كلمة مرور الحساب",
    sendCode: "إرسال رمز التحقق",
    codeSentToast: "تم إرسال رمز التحقق إلى رقمك.",
    devCodeHint: "وضع التطوير: الرمز هو",
    verificationCodeLabel: "رمز التحقق",
    newPhoneLabel: "رقم الجوال الجديد",
    confirmPhoneChange: "حفظ الرقم الجديد",
    phoneUpdated: "تم تحديث رقم الجوال.",
    phoneStep2Hint: "أدخل الرمز الذي وصلك ثم رقمك الجديد.",
    manageSecuritySettings: "الأمان",
    hideSecuritySettings: "إخفاء",
    myAdverts: "إعلاناتي",
    myAdvertsTitle: "إعلاناتي",
    myAdvertsSubtitle: "الإعلانات التي نشرتها — افتحها أو عدّلها.",
    myAdvertsEmpty: "لم تنشر أي إعلانات بعد.",
    editListing: "تعديل الإعلان",
    editListingTitle: "تعديل الإعلان",
    editListingDesc: "حدّث تفاصيل إعلانك والصور. احفظ عند الانتهاء.",
    listingUpdatedSuccess: "تم تحديث الإعلان.",
    editNotOwner: "يمكنك تعديل إعلاناتك فقط.",
    saveListing: "حفظ التغييرات",
    btnReserved: "محجوز",
    btnSold: "مباع",
    btnBackToActive: "العودة للنشط",
    btnBackToActiveHelp:
      "إلغاء حالة المحجوز/المباع إذا لم يكتمل البيع — يظهر الإعلان في البحث مرة أخرى.",
    statusReserved: "محجوز",
    statusSold: "مباع",
    statusActive: "نشط",
    listingStatusUpdated: "تم تحديث حالة الإعلان.",
    listingSoldBanner: "هذا الإعلان مُعلَم كمباع.",
    listingReservedBanner: "هذا الإعلان محجوز.",
    listingSoldNoContact: "هذه الشاحنة مباعة — إرسال الرسائل غير متاح.",
    listingInactiveNoContact:
      "الرسائل غير متاحة بينما الإعلان محجوز أو غير متاح للبيع.",
    buyerMessagesTitle: "رسائل المشترين",
    noBuyerMessages: "لا توجد رسائل بعد. عندما يتواصل مشترٍ معك سيظهر هنا.",
    fromBuyer: "من",
    yourMessagesToSellers: "رسائلك إلى البائعين",
    yourMessagesToSellersHelp: "الأسئلة التي أرسلتها عن الإعلانات — يظهر رد البائع أدناه.",
    noSentMessages: "لم ترسل أي رسائل بعد.",
    sellerReplyLabel: "رد البائع",
    yourReplyLabel: "ردك",
    replyPlaceholder: "اكتب ردك للمشتري…",
    sendReply: "إرسال الرد",
    replyEmpty: "الرد لا يمكن أن يكون فارغاً.",
    replyFailed: "تعذر إرسال الرد.",
    replySentSuccess: "تم إرسال الرد.",
    yourMessageToSeller: "رسالتك",
    waitingForSellerReply: "لم يرد البائع بعد.",
    chatNotificationsTitle: "الرسائل",
    noChatThreads: "لا محادثات بعد.",
    openAccountMessages: "الحساب وجميع المحادثات",
    openChat: "فتح المحادثة",
    unreadMessages: "غير مقروء",
    chatLoadFailed: "تعذر تحميل المحادثة.",
    chatInvalidThread: "محادثة غير صالحة.",
    chatYouAreSeller: "أنت البائع في هذه المحادثة.",
    chatYouAreBuyer: "تواصلت مع البائع عن هذا الإعلان.",
    viewListing: "عرض الإعلان",
    chatReplyPlaceholder: "اكتب رسالة… (Enter للإرسال، Shift+Enter سطر جديد)",
    sellerPhoneLabel: "رقم الهاتف",
    sellerPhoneHelp: "يمكن للمشترين الاتصال بك على هذا الرقم بخصوص هذا الإعلان.",
    loginToSendMessage: "سجّل الدخول لإرسال رسالة إلى البائع.",
    sendMessageAction: "إرسال الرسالة",
    messagePlaceholder: "اكتب رسالتك…",
    messageSentSuccess: "تم إرسال الرسالة.",
    messageSendFailed: "تعذر إرسال الرسالة.",
    ownListingNoMessage: "هذا إعلانك.",
    listingCannotReceiveMessages: "لا يمكن استقبال رسائل لهذا الإعلان.",

    // Home Page
    heroTitle: "اعثر على شاحنتك التجارية المثالية",
    heroSubtitle: "تصفح آلاف الشاحنات المستعملة والتجارية عالية الجودة من بائعين موثوقين في جميع أنحاء البلاد",
    browseInventory: "تصفح المركبات",
    listYourTruck: "أضف إعلان",
    
    // Features
    advancedSearch: "بحث متقدم",
    advancedSearchDesc: "قم بالتصفية حسب العلامة التجارية والطراز والسنة والسعر والمسافة المقطوعة والمزيد للعثور على ما تحتاجه بالضبط",
    trustedSellers: "بائعون موثوقون",
    trustedSellersDesc: "اشترِ من بائعين أفراد معتمدين ووكلاء تجاريين موثوقين",
    bestPrices: "أفضل الأسعار",
    bestPricesDesc: "أسعار تنافسية على شاحنات عالية الجودة مع تسعير شفاف ومواصفات مفصلة",
    
    // Featured Section
    featuredTrucks: "شاحنات مميزة",
    viewAll: "عرض الكل",
    loading: "جاري التحميل…",
    loadFailed: "تعذر تحميل القوائم. هل واجهة البرمجة تعمل؟",
    
    // CTA
    readyToSell: "هل أنت مستعد لبيع شاحنتك؟",
    readyToSellDesc: "أدرج شاحنتك مجانًا وتواصل مع آلاف المشترين المحتملين. الأفراد والشركات مرحب بهم.",
    getStarted: "ابدأ الآن",
    
    // Categories
    allTrucks: "جميع الشاحنات",
    traditional: "تقليدية",
    lightCommercial: "مركبة تجارية خفيفة",
    constructionEquipment: "معدات بناء",
    catTractorhead: "رأس مقطورة",
    catTruckRigid: "شاحنة",
    catLightCommercialVehicle: "مركبة تجارية خفيفة",
    catConstructionEquipment: "معدات إنشاءات",
    catSemiTrailer: "مقطورة نصفية",

    // Truck Types
    commercial: "تجارية",
    pickup: "بيك أب",
    van: "فان",
    dump: "قلاب",
    flatbed: "سرير مسطح",
    semi: "شاحنة نصفية",
    
    // Inventory Page
    browseInventoryTitle: "تصفح المركبات",
    searchPlaceholder: "البحث حسب العلامة التجارية أو الطراز أو الموقع...",
    sortBy: "ترتيب حسب",
    filters: "الفلاتر",
    clear: "مسح",
    clearAllFilters: "مسح جميع الفلاتر",
    showingResults: "عرض",
    of: "من",
    trucks: "شاحنات",
    noTrucksFound: "لم يتم العثور على شاحنات تطابق معاييرك",
    
    // Sort Options
    newestFirst: "الأحدث أولاً",
    priceLowToHigh: "السعر: من الأقل إلى الأعلى",
    priceHighToLow: "السعر: من الأعلى إلى الأقل",
    yearNewest: "السنة: الأحدث",
    yearOldest: "السنة: الأقدم",
    mileageLowToHigh: "المسافة: من الأقل إلى الأعلى",
    mileageHighToLow: "المسافة: من الأعلى إلى الأقل",
    
    // Filters
    truckType: "نوع الشاحنة",
    condition: "الحالة",
    priceRange: "نطاق السعر",
    yearRange: "السنة",
    mileageRange: "المسافة المقطوعة",
    transmission: "ناقل الحركة",
    fuelType: "نوع الوقود",
    sellerType: "نوع البائع",
    
    // Condition
    excellent: "ممتاز",
    good: "جيد",
    fair: "مقبول",
    notWorking: "لا تعمل",
    
    // Transmission
    automatic: "أوتوماتيك",
    manual: "يدوي",
    
    // Fuel Type
    diesel: "ديزل",
    gasoline: "بنزين",
    electric: "كهربائي",
    hybrid: "هجين",
    
    // Seller Type
    individual: "فرد",
    company: "شركة",
    
    // Truck Card
    miles: "ميل",
    listingRef: "المرجع",
    
    // Truck Detail
    back: "رجوع",
    mileage: "المسافة المقطوعة",
    year: "السنة",
    description: "الوصف",
    features: "المميزات",
    sellerInformation: "معلومات البائع",
    callSeller: "اتصل بالبائع",
    sendMessage: "إرسال رسالة",
    additionalInformation: "معلومات إضافية",
    listed: "تاريخ الإدراج",
    type: "النوع",
    interestedTitle: "مهتم بهذه الشاحنة؟",
    interestedDesc: "اتصل بالبائع مباشرة لجدولة معاينة أو الحصول على مزيد من المعلومات.",
    requestInformation: "طلب معلومات",
    truckNotFound: "الشاحنة غير موجودة",
    backToInventory: "العودة إلى المخزون",
    
    // Add Truck Page
    listTruckTitle: "أدرج شاحنتك للبيع",
    listTruckDesc: "املأ النموذج أدناه لإضافة شاحنتك إلى سوقنا",
    sellFlowTitle: "بيع شاحناتك",
    sellFlowQuestion: "ماذا تريد بيعه؟",
    sellContinue: "متابعة",
    changeCategory: "تغيير الفئة",
    typeLockedHint:
      "نوع المركبة مضبوط حسب الفئة التي اخترتها. يمكنك كتابة أي صانع أو طراز إذا لم يظهر في القائمة.",
    sellCatTractorUnit: "رأس مقطورة",
    sellCatRigidTruck: "شاحنة",
    sellCatSemiTrailers: "نصف مقطورة",
    sellCatVan: "فان",
    sellCatAgriculture: "زراعية",
    sellCatMachine: "آلة / معدات",
    sellCatVarious: "متنوع",

    aiCategoryStepHint:
      "ارفع صورة للمركبة وسنقترح أفضل فئة (يتطلب إعداد الخادم).",
    aiCategorySuggestFromPhoto: "اقتراح الفئة من الصورة",
    aiCategorySelectedToast: "الفئة المقترحة: {label}",
    aiCategoryUnavailable:
      "لم يُضبط كشف الفئة بالذكاء الاصطناعي على الخادم (OPENAI_API_KEY).",
    aiCategoryFailed: "تعذر تحليل الصورة. أعد المحاولة أو اختر الفئة يدوياً.",
    aiCategoryAnalyzing: "جاري تحليل الصورة الأولى للفئة…",
    aiCategorySuggestionTitle: "اقتراح الفئة",
    aiCategorySuggestionBody:
      "تبدو الصورة كـ {label} (حوالي {percent}٪ ثقة). طبّق الاقتراح أو أبقِ فئتك الحالية.",
    aiCategoryApplySuggestion: "تطبيق الاقتراح",
    aiCategoryKeepChoice: "الإبقاء على الحالي",
    basicInformation: "معلومات أساسية",
    make: "العلامة التجارية",
    model: "الطراز",
    selectMakePlaceholder: "اختر الصانع…",
    selectModelPlaceholder: "اختر الطراز…",
    selectMakeFirstModel: "اختر الصانع أولاً",
    searchMakePlaceholder: "ابحث عن الصانع…",
    searchModelPlaceholder: "ابحث عن الطراز…",
    comboboxEmptyMakes: "لا توجد علامات في المخزون — اكتب لإضافة واحدة",
    comboboxEmptyModels: "لا توجد طرازات لهذا الصانع — اكتب لإضافة واحد",
    selectYearPlaceholder: "اختر السنة…",
    comboboxEmptyYears: "لا توجد سنوات مطابقة",
    trailerMakeModelHint:
      "نصف المقطورات والمقطورات غالباً لا تظهر أسماء العلامات في القائمة. أدخل على الأقل العلامة أو الطراز/المواصفات (مثل الطول أو السلسلة). يمكنك ملء حقل واحد وترك الآخر فارغاً.",
    makeOrModelRequired: "أدخل العلامة أو الطراز على الأقل.",
    selectModelTrailerPlaceholder: "مثلاً: السلسلة، الطول، أو المواصفات",
    useCustomValue: "استخدم \"{value}\"",
    price: "السعر (ريال سعودي)",
    location: "الموقع",
    listingState: "المنطقة",
    listingCity: "المدينة",
    selectStatePlaceholder: "اختر المنطقة…",
    selectCityPlaceholder: "اختر المدينة…",
    selectStateFirstCity: "اختر المنطقة أولاً",
    comboboxEmptyRegions: "لا توجد مناطق مطابقة",
    comboboxEmptyCities: "لا توجد مدن مطابقة",
    truckDetails: "تفاصيل الشاحنة",
    companyName: "اسم الشركة",
    yourName: "اسمك",
    descriptionAndFeatures: "الوصف والمميزات",
    descriptionPlaceholder: "اختياري — أضف تفاصيل عن شاحنتك…",
    featuresPlaceholder: "مثل: تكييف الهواء، كاميرا خلفية، بلوتوث",
    featuresSeparate: "افصل المميزات بفواصل",
    imageUploadLabel: "صور الإعلان",
    imageUploadHelp:
      "حتى 10 صور — JPEG أو PNG أو WebP أو GIF، بحد أقصى 5 ميجابايت لكل صورة. تُستخدم صورة افتراضية إذا لم ترفع صوراً.",
    imageUploading: "جاري الرفع…",
    imageUploadFailed: "تعذر رفع الصورة. حاول مرة أخرى.",
    tooManyImages: "يمكنك إضافة 10 صور كحد أقصى.",
    videoUploadLabel: "فيديو الإعلان (اختياري)",
    videoUploadHelp: "MP4 أو WebM أو MOV — بحد أقصى 80 ميجابايت.",
    videoUploading: "جاري رفع الفيديو…",
    videoUploadFailed: "تعذر رفع الفيديو. حاول مرة أخرى.",
    removeVideo: "إزالة الفيديو",
    listTruck: "إدراج الشاحنة",
    cancel: "إلغاء",
    
    // Form Validation
    optional: "اختياري",
    required: "مطلوب",
    yearMin: "يجب أن تكون السنة 1970 أو أحدث",
    yearMax: "لا يمكن أن تكون السنة في المستقبل",
    mileageMin: "يجب أن تكون المسافة المقطوعة موجبة",
    priceMin: "يجب أن يكون السعر موجبًا",
    descriptionMin: "يجب أن يكون الوصف 50 حرفًا على الأقل",
    
    // Toast Messages
    truckAddedSuccess: "تمت إضافة إعلان الشاحنة بنجاح!",
    saveFailed: "تعذر حفظ الإعلان. حاول مرة أخرى.",
    
    // 404 Page
    pageNotFound: "الصفحة غير موجودة",
    pageNotFoundDesc: "الصفحة التي تبحث عنها غير موجودة أو تم نقلها.",
    goBackHome: "العودة إلى الصفحة الرئيسية",

    // Site footer
    footerColBuy: "الشراء",
    footerViewStock: "عرض المخزون",
    footerHowToBuy: "كيفية شراء مركبة",
    footerColSell: "البيع",
    footerStartSelling: "ابدأ البيع",
    footerColHelp: "المساعدة",
    footerContact: "اتصل بنا",
    footerCareers: "الوظائف",
    footerColLearn: "تعرّف",
    footerAbout: "عن MarketSmart",
    footerNews: "الأخبار",
    footerEthics: "الأخلاقيات",
    footerSubscribeNewsletter: "اشترك في النشرة الإخبارية",
    footerPrivacy: "سياسة الخصوصية",
    footerCookie: "سياسة ملفات تعريف الارتباط",
    footerSitemap: "خريطة الموقع",
    footerCopyright: "© حقوق النشر 2026 MarketSmart",
    footerAnyQuestions: "أي أسئلة؟",
    footerDismissQuestionWidget: "إخفاء",
    footerSocialAria: "MarketSmart على {network}",
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("en");

  useEffect(() => {
    document.documentElement.lang = language === "ar" ? "ar" : "en";
    document.documentElement.dir = language === "ar" ? "rtl" : "ltr";
  }, [language]);

  const toggleLanguage = () => {
    setLanguage((prev) => (prev === "en" ? "ar" : "en"));
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.en] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
}
